contacts={"Boxing Promoters", 
"Organized Crime", 
"Sports Writers", 
"Old Military Buddies", 
"Commercial Pilots", 
"Airplane Mechanics", 
"Airfields", 
"Aircraft Manufacturers", 
"Local Government", 
"Game Wardens", 
"Previous Clients", 
"Celebrity", 
"Coast Guard", 
"Smugglers", 
"Libraries", 
"Universities", 
"Monied Patrons", 
"Explorers", 
"Publishers", 
"Foreign Government", 
"Mountain Climbers", 
"Park Rangers", 
"Auto Manufacturers", 
"Boat Manufacturers", 
"Film Industry", 
"Investors", 
"Treasure Hunters", 
"Local Law Officials", 
"Art Galleries", 
"Art Critics", 
"Advertising Industry", 
"Stage Contacts", 
"Furnishings Industry", 
"Architects", 
"Local Building/City Engineering Departments", 
"Construction Firms", 
"News Industry", 
"Film Manufacturers", 
"Camera Manufacturers", 
"Writers", 
"Publishing Industry", 
"Vaudeville", 
"Broadway Stage", 
"Entertainment Critics", 
"Film Unions", 
"Newspaper Critics", 
"Actor's Guild", 
"Music Club Owners", 
"Musician's Union", 
"Street Scene", 
"Drug Pushers", 
"Musicians", 
"Theatre Industry", 
"Explosive and Pyrotechnic Firms", 
"Free Lance Inventors", 
"Amateur Athletic Circles", 
"Circuses", 
"Carnivals", 
"Sports Professionals", 
"Wealthy / Influential Club Members", 
"Athletic Circles", 
"Wealthy / Influential Alumnae", 
"Sports Personalities", 
"Gamblers", 
"Tennis Pros", 
"Medical Professionals", 
"Office Workers", 
"Business World", 
"Finance World", 
"College Connections", 
"Masons or other Fraternal Groups", 
"Federal Government", 
"Magazine Industry", 
"Local Residents", 
"Business Suppliers", 
"Customers", 
"Religious Publishers", 
"Church Hierarchy", 
"Local Congregation", 
"Community Leaders", 
"Movie Stars", 
"Rich Widows", 
"Local Businesses", 
"God", 
"Jewish Scholars", 
"Local Jewish Community", 
"Gang Members", 
"Friends and Family of Gang Members", 
"Local Ethnic Community", 
"Fences", 
"Burglars", 
"Con Men", 
"Street  Criminals", 
"Businessmen", 
"Bookies", 
"Police", 
"Politicians", 
"Judges", 
"District Attorneys", 
"Local Church", 
"Underworld", 
"Debtors", 
"Punks", 
"U.S. Customs", 
"Golf Pros", 
"Accountants", 
"Suppliers", 
"Bankers", 
"Gangsters", 
"Safe House", 
"Military", 
"Radio Industry", 
"Hollywood", 
"High Society", 
"State Agricultural Department", 
"Unions", 
"Socialists", 
"Communists", 
"Subversives", 
"Bail Bondsmen", 
"Law Enforcement", 
"Local Labs", 
"Chemical Suppliers", 
"Coroner's Office", 
"Newspaper Morgues", 
"Criminals", 
"Courts", 
"Bounty Hunters", 
"Legal Connections", 
"Psychological Community", 
"Medical supplies, drugs, records", 
"Mercenary Networks", 
"Illegal Arms Dealers", 
"Small Governments", 
"Multinational Corporations", 
"Veteran's Administration", 
"Scholars", 
"Grant Foundations", 
"Local Historians", 
"Antique Dealers", 
"Artists", 
"Poets", 
"Civic Amenities", 
"Hobos", 
"Railroad Guards", 
"Seaman's Union", 
"Museum Patrons", 
"Occult Societies", 
"Occultists", 
"Parapsychological Publications", 
"Records Offices", 
"University Zoology Department", 
"Bibliographers", 
"Book Dealers"}
