humanAnatomy={"Cardiovascular system",
"Digestive system",
"Endocrine system",
"Urinary system",
"Immune system",
"Integumentary system",
"Lymphatic system",
"Muscular system",
"Nervous system",
"Reproductive system",
"Respiratory system",
"Skeletal system",
"cell",
"ovum",
"spermatozošn",
"Fertilization of ovum",
"Segmentation of fertilized ovum",
"neural groove and neural tube",
"notochord",
"primitive segments",
"Separation of embryo",
"yolk-sac",
"Development of fetal membranes and placenta",
"branchial region",
"Development of body cavities",
"form of embryo at different stages of its growth",
"Osteology",
"Bone",
"vertebral column",
"General characteristics of a vertebra",
"cervical vertebrae",
"thoracic vertebrae",
"lumbar vertebrae",
"sacral vertebrae",
"coccygeal vertebrae",
"vertebral column as a whole",
"thorax",
"sternum",
"ribs",
"costal cartilages",
"skull",
"cranial bones",
"occipital bone",
"parietal bone",
"frontal bone",
"temporal bone",
"sphenoid bone",
"ethmoid bone",
"facial bones",
"nasal bones",
"maxillae (upper jaw)",
"lacrimal bone",
"zygomatic bone",
"palatine bone",
"inferior nasal concha",
"vomer",
"mandible (lower jaw)",
"hyoid bone",
"exterior of skull",
"interior of skull",
"extremities",
"bones of upper extremity",
"clavicle",
"scapula",
"humerus",
"ulna",
"radius",
"hand",
"carpus",
"metacarpus",
"phalanges of hand",
"bones of lower extremity",
"hip bone",
"pelvis",
"femur",
"patella",
"tibia",
"fibula",
"foot",
"tarsus",
"metatarsus",
"phalanges of foot",
"sesamoid bones",
"Syndesmology",
"Development of joints",
"Classification of joints",
"kind of movement admitted in joints",
"Articulations of trunk",
"Articulations of vertebral column",
"Articulation of atlas with epistropheus or axis",
"Articulations of vertebral column with cranium",
"Articulation of mandible",
"Costovertebral articulations",
"Sternocostal articulations",
"Articulation of manubrium and body of sternum",
"Articulation of vertebral column with pelvis",
"Articulations of pelvis",
"Articulations of upper extremity",
"Sternoclavicular articulation",
"Acromioclavicular articulation",
"Humeral articulation or shoulder-joint",
"Elbow-joint",
"Radioulnar articulation",
"Radiocarpal articulation or wrist-joint",
"Intercarpal articulations",
"Carpometacarpal articulations",
"Intermetacarpal articulations",
"Metacarpophalangeal articulations",
"Articulations of digits",
"Articulations of lower extremity",
"Coxal articulation or hip-joint",
"knee-joint",
"Articulations between tibia and fibula",
"Talocrural articulation or ankle-joint",
"Intertarsal articulations",
"Tarsometatarsal articulations",
"Intermetatarsal articulations",
"Metatarsophalangeal articulations",
"Articulations of digits",
"Arches of foot",
"Myology",
"Mechanics of muscle",
"Development of muscles",
"Tendons, aponeuroses, and fasciae",
"fasciae and muscles of head.",
"muscles of scalp",
"muscles of eyelid",
"muscles of nose",
"muscles of mouth",
"muscles of mastication",
"fasciae and muscles of anterolateral region of neck",
"superficial cervical muscle",
"lateral cervical muscles",
"supra- and infrahyoid muscles",
"anterior vertebral muscles",
"lateral vertebral muscles",
"fasciae and muscles of trunk",
"deep muscles of back",
"suboccipital muscles",
"muscles of thorax",
"muscles and fasciae of abdomen",
"muscles and fasciae of pelvis",
"muscles and fasciae of perineum",
"fascia and muscles of upper extremity",
"muscles connecting upper extremity to vertebral column",
"muscles connecting upper extremity to anterior and lateral thoracic walls",
"muscles and fasciae of shoulder",
"muscles and fasciae of arm",
"muscles and fasciae of forearm",
"muscles and fasciae of hand",
"muscles and fasciae of lower extremity.",
"muscles and fasciae of iliac region",
"muscles and fasciae of thigh",
"muscles and fasciae of leg",
"fasciae around ankle",
"muscles and fasciae of foot",
"Angiology",
"blood",
"Development of vascular system",
"thoracic cavity",
"pericardium",
"heart",
"Peculiarities in vascular system in fetus",
"Arteries",
"aorta",
"arteries of head and neck",
"common carotid artery",
"Relations",
"external carotid artery",
"triangles of neck",
"internal carotid artery",
"arteries of brain",
"arteries of upper extremity",
"subclavian artery",
"axilla",
"axillary artery",
"brachial artery",
"radial artery",
"ulnar artery",
"arteries of trunk",
"descending aorta",
"thoracic aorta",
"abdominal aorta",
"common iliac arteries",
"hypogastric artery",
"external iliac artery",
"arteries of lower extremity",
"femoral artery",
"popliteal fossa",
"popliteal artery",
"anterior tibial artery",
"arteria dorsalis pedis",
"posterior tibial artery",
"Veins",
"pulmonary veins",
"systemic veins",
"veins of heart",
"veins of head and neck",
"veins of exterior of head and face",
"veins of neck",
"diploic veins",
"veins of brain",
"sinuses of dura mater. ophthalmic veins and emissary veins",
"veins of upper extremity and thorax",
"veins of lower extremity, abdomen, and pelvis",
"portal system of veins",
"Lymphatic system",
"thoractic duct",
"lymphatics of head, face, and neck",
"lymphatics of upper extremity",
"lymphatics of lower extremity",
"lymphatics of abdomen and pelvis",
"lymphatic vessels of thorax",
"Neurology",
"Structure of nervous system",
"Development of nervous system",
"spinal cord or medulla spinalis",
"brain or encephalon",
"hindbrain or rhombencephalon",
"midbrain or mesencephalon",
"forebrain or prosencephalon",
"Composition and central connections of spinal nerves",
"Composition and central connections of spinal nerves",
"Pathways from brain to spinal cord",
"meninges of brain and medulla spinalis",
"cerebrospinal fluid",
"cranial nerves",
"olfactory nerves",
"optic nerve",
"oculomotor nerve",
"trochlear nerve",
"trigeminal nerve",
"abducent nerve",
"facial nerve",
"vestibulocochlear nerve",
"glossopharyngeal nerve",
"vagus nerve",
"accessory nerve",
"hypoglossal nerve",
"spinal nerves",
"posterior divisions",
"anterior divisions",
"thoracic nerves",
"lumbosacral plexus",
"sacral and coccygeal nerves",
"sympathetic nerves",
"cephalic portion of sympathetic system",
"cervical portion of sympathetic system",
"thoracic portion of sympathetic system",
"abdominal portion of sympathetic system",
"pelvic portion of sympathetic system",
"great plexuses of sympathetic system",
"Organs of Senses and Common Integument",
"peripheral organs of special senses",
"organs of taste",
"organ of smell",
"organ of sight",
"tunics of eye",
"refracting media",
"accessory organs of eye",
"organ of hearing",
"external ear",
"middle ear or tympanic cavity",
"auditory ossicles",
"internal ear or labyrinth",
"Peripheral terminations of nerves of general sensations",
"common integument",
"Splanchnology",
"respiratory apparatus",
"larynx",
"trachea and bronchi",
"pleurae",
"mediastinum",
"lungs",
"digestive apparatus",
"mouth",
"fauces",
"pharynx",
"esophagus",
"abdomen",
"stomach",
"small intestine",
"large intestine",
"liver",
"pancreas",
"urogenital apparatus",
"Development of urinary and generative organs",
"urinary organs",
"kidneys",
"ureters",
"urinary bladder",
"male urethra",
"female urethra",
"male genital organs",
"testes and their coverings",
"ductus deferens",
"vesiculae seminales",
"ejaculatory ducts",
"penis",
"prostate",
"bulbourethral glands",
"female genital organs",
"ovaries",
"uterine tube",
"uterus",
"vagina",
"clitoris",
"Bartholin's glands",
"external organs",
"mammae",
"ductless glands",
"thyroid gland",
"parathyroid glands",
"thymus",
"hypophysis cerebri",
"pineal body",
"chromaphil and cortical systems",
"spleen"}

