lyrics={ "On one summer day...", 
"Sun was shining fine...", 
"The lady love of old Bill Bailey was", 
"hanging clothes on de line", 
"in her back yard...", 
"and weeping hard...", 
"She married a B. and G. brakeman", 
"Dat took and throw'd her down.", 
"Bellaring like a prune-fed calf", 
"wid a big gang hanging 'round;", 
"And to dat crowd...", 
"She yelled out loud:...", 
"Won't you come home, Bill Bailey", 
"won't you come home?", 
"She means de whole day long;...", 
"I'll do de cooking, darling, I'll pay de rent:", 
"I know I've done you wrong;...", 
"'Member dat rainy eve dat I drove you out", 
"Wid nothing but a fine tooth comb?", 
"I knows I'm to blame; well ain't dat a shame?", 
"Bill Bailey, won't you please come home?", 
"Bill drove by dat door...", 
"in an automobile...", 
"A great big diamond coach and fast-man", 
"hear dat big wench squeal 'he's all alone.'...", 
"I heard her grown...", 
"She holler'd thro' that door, --Bill Bailey, is you sore?", 
"Stop a minute, won't you listen to me?", 
"Won't I see you no more?' Bill winked his eye..", 
"And her heard her cry:...", 
"The ballroom was filled with fashion's throng", 
"It shone with a thousand lights", 
"And there was a woman who passed along", 
"The fairest of all the sights", 
"A girl to her lover then softly sighed", 
"There's riches at her command;", 
"But she married for wealth, not for love he cried", 
"Though she lives in a mansion grand.", 
"She's only a bird in a gilded cage", 
"A beautiful sight to see", 
"You may think she's happy and free from care", 
"She's not, though she seems to be", 
"'Tis sad when you think of her wasted life", 
"For youth cannot mate with age", 
"And her beauty was sold", 
"For an old man's gold", 
"She's a bird in a gilded cage.", 
"I stood in a churchyard just at eve'", 
"When sunset adorned the west", 
"And looked at the people who'd come to grieve", 
"For loved ones now laid at rest", 
"A tall marble monument marked the grave", 
"Of one who'd been fashion's queen", 
"And I thought she is happier here at rest", 
"Than to have people say when seen.", 
"You receive a little missive, some one leaves it in the hall", 
"By the tint you know who wrote it, scent of violets over all;", 
"And you break the seal and read it, “You may call tonight at eight,”", 
"That is what it says, “Good Bye dear, from your loving little Kate.”", 
"When you go out for a twilight call", 
"Whistling the latest air", 
"Swinging along in an easy way", 
"Happy and free from care.", 
"Hoping the sweet words you whisper tonight", 
"On willing ears may fall", 
"When at the gate, lingering with Kate", 
"Making a twilight call.", 
"How the daylight seems to linger, but at last ’tis candlelight", 
"And you trip away so happy while the stars are shining bright.", 
"Then she sees you, turn the corner, gaily waves her hand at you", 
"At the gate you’ll find her waiting, she’s your sweetheart good and true.", 
" A black man in a minstrel show", 
"was sitting on the end", 
"A nice black gal in the very front row", 
"with heaps of dough to spend", 
"look’d up at him, with a silly smile", 
"He started singing his end song", 
"forgot most ev’ry line", 
"The manager hurried back and said", 
"“You’ve got to stand a fine”—", 
"he lost his job, for quite a while.", 
"Just because she made them googoo eyes", 
"I thought I’d won a home and copp’d a prize.", 
"She is the best what is and I need her in my biz", 
"Just because she makes them googoo eyes.", 
"This minstrel man wash’d up right quick", 
"and meets her at the door", 
"Tips his hat says how do you do", 
"I’m with this troupe no more", 
"it was for you, I paid no fine", 
"I wants to ask one question now", 
"please let me call you dear", 
"It costs a lot to gain a rep", 
"But I’ll blow the road right here", 
"if you’ll be mine, if you’ll be mine.", 
"Just because she makes them googoo eyes", 
"I know I’ve won a home and copp’d a prize.", 
"You is the best what is and I wants you in my biz", 
"Just becaus you make them googoo eyes. ", 
"Next morning when the troupe had left", 
"this baby throw’d him down", 
"She said to him, “I’ll have you ‘pinched’", 
"if you stay in this town", 
"oh, listen to this tslr of woe", 
"He said I’ll send a teles patch to try and join the show", 
"What can I do in this strange land", 
"Can’t eat without no dough", 
"so here I am, out in the snow.", 
"Just because she make them googoo eyes", 
"I though I had a home and copp’d a prize.", 
"She was the best what is but drove me right back in the biz", 
"Just because she made them googoo eyes.", 
"Did you ever see two Yankees part up on a foreign shore", 
"When the good ship's just around about to start for Old New York once more?", 
"With tear-dimmed eye they say goodbye, they're friends without a doubt;", 
"When the man on the pier", 
"Shouts 'Let them clear,' as the ship strikes out.", 
"Give my regards to Broadway, remember me to Herald Square", 
"Tell all the gang at Forty Second street, that I will soon be there;", 
"Whisper of how I'm yearning", 
"To mingle with the old time throng", 
"Give my regards to old Broadway and say that I'll be there e'er long.", 
"Say hello to dear old Coney Isle, if there you chance to be", 
"When you're at the Waldorf have a smile and charge it up to me;", 
"Mention my name ev'ry place you go, as 'round the town you roam;", 
"Wish you'd call on my gal", 
"Now remember, old pal, when you get back home.", 
"The scene is a room in a flat when the gloom, ", 
"From the gas in the parlor’s dim, ", 
"Don’t frighten the maid nor the man I’m afraid, ", 
"Cause the same chair holds Mary and Jim. ", 
"Now Mary tells Jim she’ll get married to him, ", 
"And asks him to pick out the day, ", 
"Says Jim to Marie “Gee, you look good to me, ", 
"But there’s something else stands in the way.“ ", 
"I don’t like your family, ", 
"They don’t make a hit with me, ", 
"I don’t want to bother lending money to your father, ", 
"While your Ma’s relations live on me, ", 
"I don’t think your Uncle John ever had a collar on, ", 
"You’re a perfect lady but when I get hitched for life, I want an orphan.", 
"Your dad with a knife has the time of his life, ", 
"Eating pie in the good old way, ", 
"Then he and your mother throw plates at each other, ", 
"’Cause baby cuts teeth night and day. ", 
"Next dear little Anna torments the piano, ", 
"While Willie plays tunes on a comb, ", 
"All this might go well in a big padded cell, ", 
"It’s not my dream of “Home, Sweet Home.”", 
"1. I’ve lost a dog, my daddy bought me;", 
"He was a bad dog, ?cause he fought me;", 
"Tore my dress and ran away.", 
"When with him I tried to play.", 
"So, my ma said, just for that", 
"I should adopt a Pussy cat.", 
"And I’ve git ine now, you know", 
"I can take around and show.", 
"Have you seen my Pussy cat, Pussy cat, Pussy cat?", 
"Have you seen my Pussy cat?", 
"With her cute little me’owow ow.", 
"My little puss is cure and frisky;", 
"Likes to explore the things thats risky", 
"That’s why she met one mishap", 
"When I hid her in my lap.", 
"Up came a Tom cat, big and black;", 
"Humped up his spine, gave her a whack;", 
"But Puss snapped and he turned pale", 
"When he found he’d lost his tail.", 
"Down at the seashore I was standing;", 
"Watching the bathers from the landing", 
"With my hand I held puss tight;", 
"’Fraid the boys might give her fright.", 
"All of a sudden my feet slipped;", 
"I heard a noise like something ripped!", 
"When they hauld us back on land", 
"My poor puss was full of sand.", 
"The night was mighty dark so you could hardly see", 
"For the moon refused to shine", 
"Couple sitting underneath a willow tree", 
"For love they pine", 
"Little maid was kind afraid of darkness", 
"So she said, 'I guess I'll go,'", 
"Boy began to sigh", 
"Looked up at the sky", 
"Told the moon his little tale of woe.", 
"Oh, shine on, shine on harvest moon up in the sky.", 
"I ain't had no lovin'", 
"Since April, January June or July", 
"Snow time ain't no time to stay out doors and spoon", 
"So, shine on, shine on, harvest moon", 
"For me and my gal.", 
"I can't see why a boy should sigh, when by his side", 
"is the girl he love so true", 
"All he has to say is 'Won't you be my bride", 
"For I love you", 
"Why should I be telling you this secret", 
"When I know that you can guess,'", 
"Harvest moon will smile", 
"Shine on all the while", 
"If the little girl should answer 'Yes.'", 
"You have loved lots of girls in the sweet long ago", 
"And each one has meant Heaven to you.", 
"You have vowed your affection to each one in turn", 
"And have sworn to them all you'd be true.", 
"You have kissed 'neath the moon while the world seemed in tune", 
"They you've left her to hunt a new game.", 
"Does it ever occur to you later my boy", 
"That she's probably doing the same?", 
"I wonder who's kissing her now", 
"Wonder who's teaching her now", 
"Wonder who's looking into her eyes", 
"Breathing sighs, telling lies;", 
"I wonder who's buying the wine", 
"For lips that I used to call mine.", 
"Wonder if she ever tells him of me", 
"I wonder who's kissing her now.", 
"If you wantr to feel wretched and lonely and blue", 
"Just imaging the girl you love best", 
"In the arms of some fellow who's stealing a kiss", 
"From the lips that you once fondly pressed;", 
"But the world moves a-pace and the loves of today", 
"Flit away with a smile and a tear", 
"So you never can tell who is kissing her now", 
"Or just whom you'll be kissing next year.", 
"O beautiful for spacious skies", 
"For amber waves of grain", 
"For purple mountain majesties", 
"Above the fruited plain!", 
"America! America!", 
"God shed His grace on thee", 
"And crown thy good with brotherhood", 
"From sea to shining sea.", 
"O beautiful for pilgrim feet", 
"Whose stern, impassioned stress", 
"A thoroughfare for freedom beat", 
"Across the wilderness!", 
"America! America!", 
"God mend thine ev-ery flaw", 
"Confirm thy soul in self-control", 
"Thy liberty in law.", 
"O beautiful for heroes proved", 
"In liberating strife", 
"Who more that self their country loved", 
"And mercy more than life!", 
"America! America!", 
"May God thy gold refine", 
"Till all success be nobelness", 
"And ev-ery gain divine.", 
"O beautiful for patriot dream", 
"That sees beyond the years", 
"Thine alabaster cities gleam", 
"Undimmed by human tears!", 
"America! America!", 
"God shed His grace on thee", 
"And crown thy good with brotherhood", 
"From sea to shining sea.", 
"I am dreaming Dear of you", 
"Day by day", 
"Dreaming when the skies are blue", 
"When they're gray;", 
"When the silv'ry moonlight gleams", 
"Still I wander on in dreams", 
"In a land of love, it seems", 
"Just with you.", 
"Let me call you 'Sweetheart' I'm in love with you.", 
"Let me hear you whisper that you love me too.", 
"Keep the lovelight glowing in your eyes so true.", 
"Let me call you 'Sweetheart' I'm in love with you.", 
"Longing for you all the while", 
"More and more", 
"Longing for the sunny smile", 
"I adore;", 
"Birds are singing far and near", 
"Roses blooming ev'rywhere", 
"You, alone, my heart can cheer", 
"You just you.", 
"Oh, Danny Boy the pipes are calling", 
"From glen to glen, and down the mountain side", 
"The summer's gone and all the roses falling", 
"It's you, it's you must go, and I must bide", 
"But come ye back when summer's in the meadow", 
"Or when the valley's hushed and white with snow.", 
"It's I'll be here in sunshine or in shadow", 
"Oh, Danny Boy, oh Danny Boy, I love you son!", 
"But when ye come, and all the flow'rs are dying", 
"If I am dead, as dead I well may be", 
"Ye'll come and fine the place where I am lying", 
"And kneel and say an A-ve there for me;", 
"And I shall hear though soft you tread above me", 
"And all my grave will warmer, sweeter be", 
"For you will bend and tell me that you love me", 
"And I shall sleep in peace until you come to me!", 
"Tommy Atkins is a warrior bold ", 
"Merrie England loves him more than gold ", 
"And to France the hero of today ", 
"is fighting in the trenches, miles away ", 
"Now Billy Boy, has gane across the sea ", 
"to help them in their fight for Liberty.", 
"Billy Boy, Billy Boy ", 
"you’re a soldier of renown ", 
"Billy Boy, Billy Boy ", 
"in a uniform of brown ", 
"What a grand old sight ", 
"As you battle for the right ", 
"Billy Boy, Billy Boy ", 
"with a heart so fond and true ", 
"for the Red, White and Blue, ", 
"you are loyal thro’ and thro’ ", 
"you put the “Brave” in Bravery ", 
"you are my pride and joy ", 
"Now let the bugle blow, ", 
"come on come on let’s go ", 
"“Atta” boy my Billy Boy. ", 
"Billy Boy.", 
"There is Russia with a mighty host, ", 
"Of her sturdy cossacks she can boast ", 
"And for valor no one can forget ", 
"those fearless Belgian lads who’re ", 
"fighting yet Now Billy Boy, its put right up to you ", 
"to help them win so show what you can do.", 
"A gang of good fellows are we, (are we,)", 
"are we, (are we,) are we, (are we,)", 
"With never a worry you see, (you see,) ", 
"you see, (you see,) you see, (you see,) ", 
"We laugh and joke, we sing and smoke", 
"And live life merrily;", 
"No matter the weather", 
"when we get together", 
"we have a jubilee.", 
"Hail! Hail! the gang's all here", 
"What the _duece_ do we care", 
"What the _duece_ do we care", 
"Hail! Hail! we're full of cheer", 
"What the _duece_ do we care Bill!", 
"We love one another we do, (we do,) ", 
"we do, (we do,) we do, (we do,) ", 
"With brotherly love and it's true, (it's true,) ", 
"it's true, (it's true,) it's true, (it's true,) ", 
"It's one for all, the big and small", 
"It's always me for you;", 
"No matter the weather", 
"when we get together", 
"we drink a toast for two.", 
"When out for a good time we go, (we go,) ", 
"we go, (we go,) we go, (we go,) ", 
"There nothing we do that is slow, (is slow,) ", 
"is slow, (is slow,) is slow, (is slow,) ", 
"Of joy we get our share you bet", 
"The gang will tell you so;", 
"No matter the weather", 
"when we get together", 
"we sing this song you know:", 
"Yesterday I heard a lover sigh", 
"“Goodbye oh me, oh my”", 
"Seven times he got aboard his train", 
"And seven times he hurries back", 
"to kiss his love again, and tell her:—", 
"“Toot, toot, Tootsie, Goo’ Bye!", 
"Toot, toot, Tootsie, don’t cry", 
"The choo choo train that takes me", 
"Away from you no words can tell how sad it makes me", 
"Kiss me, Tootsie, and then", 
"Do it over again", 
"Watch for the mail", 
"I’ll never fail", 
"If you don’t get a letter then you’ll know I’m in jail", 
"Tut, tut, tootsie don’t cry", 
"Toot, toot, Tootsie, Goo’ Bye!”", 
"Tootsie, Goo’Bye!", 
"When somebody says goodbye to me", 
"I’m sad as I can be", 
"Not so with this loving Romeo", 
"He seemed to take a lot of pleasure", 
"saying byebye to his treasure",
"There were not many at that lonely place,",
"Where two scourged hills met in a little plain.",
"The wind cried loud in gusts, then low again.",
"Three pines strained darkly, runners in a race",
"Unseen by any. Toward the further woods",
"A dim harsh noise of voices rose and ceased.",
"-- We were most silent in those solitudes --",
"Then, sudden as a flame, the black-robed priest,",
"The clotted earth piled roughly up about",
"The hacked red oblong of the new-made thing,",
"Short words in swordlike Latin -- and a rout",
"Of dreams most impotent, unwearying.",
"Then, like a blind door shut on a carouse,",
"The terrible bareness of the soul's last house.",
"Onward to her destination,",
"O'er the stream the Hannah sped,",
"When a cry of consternation",
"Smote and chilled our hearts with dread.",
"Wildly leaping, madly sweeping,",
"All relentless in their sway,",
"Like a band of cruel demons",
"Flames were closing 'round our way",
"Oh! the horror of those moments;",
"Flames above and waves below -",
"Oh! the agony of ages",
"Crowded in one hour of woe.",
"Fainter grew our hearts with anguish",
"In that hour with peril rife,",
"When we saw the pilot flying,",
"Terror-stricken, for his life.",
"Then a man uprose before us -",
"We had once despised his race -",
"But we saw a lofty purpose",
"Lighting up his darkened face.",
"While the flames were madly roaring,",
"With a courage grand and high,",
"Forth he rushed unto our rescue,",
"Strong to suffer, brave to die.",
"Helplessly the boat was drifting,",
"Death was staring in each face,",
"When he grasped the fallen rudder,",
"Took the pilot's vacant place.",
"Could he save us? Would he save us?",
"All his hope of life give o'er?",
"Could he hold that fated vessel",
"'Till she reached the nearer shore?",
"All our hopes and fears were centered",
"'Round his strong, unfaltering hand;",
"If he failed us we must perish,",
"Perish just in sight of land.",
"Breathlessly we watched and waited",
"While the flames were raging fast;",
"When our anguish changed to rapture -",
"We were saved, yes, saved at last.",
"Never strains of sweetest music",
"Brought to us more welcome sound",
"Than the grating of that steamer",
"When her keel had touched the ground.",
"But our faithful martyr hero",
"Through a fiery pathway trod,",
"Till he laid his valiant spirit",
"On the bosom of his God.",
"Fame has never crowned a hero",
"On the crimson fields of strife,",
"Grander, nobler, than that pilot",
"Yielding up for us his life.",
"When grace is given us ever to behold",
"A child some sweet months old,",
"Love, laying across our lips his finger, saith,",
"Smiling, with bated breath,",
"Hush! for the holiest thing that lives is here,",
"And heaven’s own heart how near!",
"How dare we, that may gaze not on the sun,",
"Gaze on this verier one?",
"Heart, hold thy peace; eyes, be cast down for shame;",
"Lips, breathe not yet its name.",
"In heaven they know what name to call it; we,",
"How should we know? For, see!",
"The adorable sweet living marvellous",
"Strange light that lightens us",
"Who gaze, desertless of such glorious grace,",
"Full in a babe’s warm face!",
"All roses that the morning rears are nought,",
"All stars not worth a thought,",
"Set this one star against them, or suppose",
"As rival this one rose.",
"What price could pay with earth’s whole weight of geld",
"One least flushed roseleafs fold",
"Of all this dimpling store of smiles that shine",
"From each warm curve and line,",
"Each charm of flower-sweet flesh, to reillume",
"The dappled rose-red bloom",
"Of all its dainty body, honey-sweet",
"Clenched hands and curled-up feet,",
"That on the roses of the dawn have trod",
"As they came down from God,",
"And keep the flush and colour that the sky",
"Takes when the sun comes nigh,",
"And keep the likeness of the smile their grace",
"Evoked on God’s own face",
"When, seeing this work of his most heavenly mood,",
"He saw that it was good?",
"For all its warm sweet body seems one smile,",
"And mere men’s love too vile",
"To meet it, or with eyes that worship dims",
"Read o’er the little limbs,",
"Read all the book of all their beauties o’er,",
"Rejoice, revere, adore,",
"Bow down and worship each delight in turn,",
"Laugh, wonder, yield, and yearn.",
"But when our trembling kisses dare, yet dread,",
"Even to draw nigh its head,",
"And touch, and scarce with touch or breath surprise",
"Its mild miraculous eyes",
"Out of their viewless vision, O, what then,",
"What may be said of men?",
"What speech may name a new-born child? what word",
"Earth ever spake or heard?",
"The best men’s tongue that ever glory knew",
"Called that a drop of dew",
"Which from the breathing creature’s kindly womb",
"Came forth in blameless bloom.",
"We have no word, as had those men most high,",
"To call a baby by.",
"Rose, ruby, lily, pearl of stormless seas,",
"A better word than these,",
"A better sign it was than flower or gem",
"That love revealed to them:",
"They knew that whence comes light or quickening flame,",
"Thence only this thing came,",
"And only might be likened of our love",
"To somewhat born above,",
"Not even to sweetest things dropped else on earth,",
"Only to dew’s own birth.",
"Nor doubt we but their sense was heavenly true,",
"Babe, when we gaze on you,",
"A dew-drop out of heaven whose colours are",
"More bright than sun or star,",
"As now, ere watching love dare fear or hope,",
"Lips, hands, and eyelids ope,",
"And all your life is mixed with earthly leaven.",
"O child, what news from heaven?",
"When grace is given us ever to behold",
"A child some sweet months old,",
"Love, laying across our lips his finger, saith,",
"Smiling, with bated breath,",
"Hush! for the holiest thing that lives is here,",
"And heaven’s own heart how near!",
"How dare we, that may gaze not on the sun,",
"Gaze on this verier one?",
"Heart, hold thy peace; eyes, be cast down for shame;",
"Lips, breathe not yet its name.",
"In heaven they know what name to call it; we,",
"How should we know? For, see!",
"The adorable sweet living marvellous",
"Strange light that lightens us",
"Who gaze, desertless of such glorious grace,",
"Full in a babe’s warm face!",
"All roses that the morning rears are nought,",
"All stars not worth a thought,",
"Set this one star against them, or suppose",
"As rival this one rose.",
"What price could pay with earth’s whole weight of geld",
"One least flushed roseleafs fold",
"Of all this dimpling store of smiles that shine",
"From each warm curve and line,",
"Each charm of flower-sweet flesh, to reillume",
"The dappled rose-red bloom",
"Of all its dainty body, honey-sweet",
"Clenched hands and curled-up feet,",
"That on the roses of the dawn have trod",
"As they came down from God,",
"And keep the flush and colour that the sky",
"Takes when the sun comes nigh,",
"And keep the likeness of the smile their grace",
"Evoked on God’s own face",
"When, seeing this work of his most heavenly mood,",
"He saw that it was good?",
"For all its warm sweet body seems one smile,",
"And mere men’s love too vile",
"To meet it, or with eyes that worship dims",
"Read o’er the little limbs,",
"Read all the book of all their beauties o’er,",
"Rejoice, revere, adore,",
"Bow down and worship each delight in turn,",
"Laugh, wonder, yield, and yearn.",
"But when our trembling kisses dare, yet dread,",
"Even to draw nigh its head,",
"And touch, and scarce with touch or breath surprise",
"Its mild miraculous eyes",
"Out of their viewless vision, O, what then,",
"What may be said of men?",
"What speech may name a new-born child? what word",
"Earth ever spake or heard?",
"The best men’s tongue that ever glory knew",
"Called that a drop of dew",
"Which from the breathing creature’s kindly womb",
"Came forth in blameless bloom.",
"We have no word, as had those men most high,",
"To call a baby by.",
"Rose, ruby, lily, pearl of stormless seas,",
"A better word than these,",
"A better sign it was than flower or gem",
"That love revealed to them:",
"They knew that whence comes light or quickening flame,",
"Thence only this thing came,",
"And only might be likened of our love",
"To somewhat born above,",
"Not even to sweetest things dropped else on earth,",
"Only to dew’s own birth.",
"Nor doubt we but their sense was heavenly true,",
"Babe, when we gaze on you,",
"A dew-drop out of heaven whose colours are",
"More bright than sun or star,",
"As now, ere watching love dare fear or hope,",
"Lips, hands, and eyelids ope,",
"And all your life is mixed with earthly leaven.",
"O child, what news from heaven?",
"All the moon-shed nights are over,",
"And the days of gray and dun;",
"There is neither may nor clover,",
"And the day and night are one.",
"Not an hamlet, not a city",
"Meets our strained and tearless eyes;",
"In the plain without a pity,",
"Where the wan grass droops and dies.",
"We shall wander through the meaning",
"Of a day and see no light,",
"For our lichened arms are leaning",
"On the ends of endless night.",
"We, the children of Astarte,",
"Dear abortions of the moon,",
"In a gay and silent party,",
"We are riding to you soon.",
"Burning ramparts, ever burning!",
"To the flame which never dies",
"We are yearning, yearning, yearning,",
"With our gay and tearless eyes.",
"In the plain without a pity,",
"(Not an hamlet, not a city)",
"Where the wan grass droops and dies.",
"Heaped in raven loops and masses",
"Over temples smooth and fair,",
"Have you marked it, as she passes,",
"Gleam and shadow mingled there,",
"Braided strands of midnight air,",
"Helen's hair?",
"Deep with dreams and starry mazes",
"Of the thought that in them lies,",
"Have you seen them, as she raises",
"Them in gladness or surprise,",
"Two gray gleams of daybreak skies,",
"Helen's eyes?",
"Moist with dew and honied wafters",
"Of a music sweet that slips,",
"Have you marked them, brimmed with laughter's",
"Song and sunshine to their tips,",
"Rose-buds whence the fragrance drips,",
"Helen's lips?",
"He who sees her needs must love her:",
"But, beware! avoid love's dart!",
"He who loves her must discover",
"Nature overlooked one part,",
"In this masterpiece of art",
"Helen's heart.",
"Heaped in raven loops and masses",
"Over temples smooth and fair,",
"Have you marked it, as she passes,",
"Gleam and shadow mingled there,",
"Braided strands of midnight air,",
"Helen's hair?",
"Deep with dreams and starry mazes",
"Of the thought that in them lies,",
"Have you seen them, as she raises",
"Them in gladness or surprise,",
"Two gray gleams of daybreak skies,",
"Helen's eyes?",
"Moist with dew and honied wafters",
"Of a music sweet that slips,",
"Have you marked them, brimmed with laughter's",
"Song and sunshine to their tips,",
"Rose-buds whence the fragrance drips,",
"Helen's lips?",
"He who sees her needs must love her:",
"But, beware! avoid love's dart!",
"He who loves her must discover",
"Nature overlooked one part,",
"In this masterpiece of art",
"Helen's heart"} 


