textAdventures={"in a dark corner","in an overgrown garden","by a large woodpile","in the yard by the rubbish",
"in a weed patch","in a forest","in a thick forest","near a blasted tree",
"at a corner of the house","at the entrance to the kitchen","in the kitchen near a grimy cooker","at the scullery door",
"in a room deep with dust","in the rear turret room","in a clearing near the house","on a path",
"at the side of the house","at the back of the hallway","in a dark alcove","in a small dark room with a staircase to the east",
"on a spiral staircase","in a wide passage with steps leading to the east","on some slippery steps","on the clifftop",
"near a crumbling wall","in a gloomy passage leading north and south ","bathed in a pool of light","in an impressive vaulted hallway",
"in a hall with a heavy, locked door to the south","in the trophy room","in a cellar with barred window","on a cliff path",
"in a cupboard with hanging coat","in the front hall","in the sitting room","in the secret room",
"on steep marble stairs","in the dining room","in a deep cellar with a coffin","on a cliff path",
"in the hallway closet","in the front lobby","in a library of evil books","in a study with a desk. There is a small hole in the     wall",
"in a weird room full of cobwebs","in a very cold chamber","in a spooky room","on the cliff path near the marsh",
"on a rubble-strewn verandah","on a front porch with a door to the north","in the front tower","in a sloping corridor",
"in the upper gallery","in the marsh by a wall","in the marsh","on a soggy path",
"by some twisted railings","on a path leading through wrought iron gates","on a path by some railings","beneath the front tower",
"amongst debris from the crumbling facade","amongst large fallen brickwork","under a rotting stone arch","on a crumbling cliff top",
"Bus Shelter Bench",
"Bus Shelter",
"Field",
"Town Square",
"Public Toilets",
"Store",
"Pub",
"Pub Cellar",
"Hilly Road",
"Outside Train Station",
"Train Station",
"Ticket Office",
"Church",
"Church Interior",
"Church Upper Level",
"Church Graveyard"}
