CthulhuOccupations={
{"Aviator	1920", "Upper Lower-Lower Middle",
"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 "Electrical Repair" ,
 "Listen" ,
 "Mechanical Repair" ,
 "Navigate" ,
 "Pilot Aircraft" ,
 "Spot Hidden" ,
 "Air Navigation",
 "Spot Hidden+20", "Old Military Buddies" ,
 "Aircraft Manufacturers" ,
 "Airfields" ,
 "Commercial Pilots" ,
 "Airplane Mechanics"},

{"Big Game Hunter", "Lower Middle-Upper Middle",
	"Bargain" ,
 "First Aid" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Hide" ,
 "Jump" ,
 "Knife" ,
 "Listen" ,
 "Natural History" ,
 "Navigate" ,
 "Choose:Other Language,1,*Language" ,
 "Sneak" ,
 "Track	", "Local Government" ,
 "Game Wardens" ,
 "Previous Clients" ,
 "Celebrity	Big game hunters stay cool when charged by large animals (even monsters). Calculate sanity losses as usual but the investigator does not suffer any adverse effects until after the incident is resolved."},

{"Charter Boat Captain",	1920,"Lower Middle+", "Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 "First Aid" ,
 "Listen" ,
 "Natural History[Natural History (Marine)]" ,
 "Navigate" ,
 "Persuade" ,
 "Pilot Boat" ,
 "Spot Hidden	","Spot Hidden+20", "Coast Guard" ,
 "Organized Crime" ,
 "Smugglers"},

{"Deep-Sea Diver",	1920	,"Upper Lower-Middle",	"Diving" ,
 "Mechanical Repair" ,
 "Natural History[Natural History (Marine)]" ,
 "Pilot Boat" ,
 "Spot Hidden" ,
 "Swim	","Spot Hidden+20","CON=1", "Coast Guard" ,
 "Smugglers"},

{"Explorer",	1920	,"Middle+", "Climb" ,
 "Dodge" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "First Aid" ,
 "History" ,
 "Jump" ,
 "Medicine" ,
 "Natural History" ,
 "Navigate" ,
 "Choose:Other Language,1,*Language" ,
 "Photography" ,
 "Swim" ,
 "Archaeology" ,
 "Anthropology", "CON=1	Libraries" ,
 "Universities" ,
 "Monied Patrons" ,
 "Explorers" ,
 "Publishers" ,
 "Foreign Government	 Add 20 points to Persuade roll whenever dealing with a primitive people or a foreign government."},

{"Mountain Climber", "Lower Middle+", "Climb" ,
 "First Aid" ,
 "Jump" ,
 "Listen" ,
 "Navigate" ,
 "Choose:Other Language,1,*Language" ,
 "Photography" ,
 "Track", "CON=1" ,
 "STR=1	Mountain Climbers" ,
 "Park Rangers" ,
 "Foreign Government" ,
 "Monied Patrons	Will never suffer from fear of heights unless specifically struck by a phobia."},

{"Prospector", "Pauper-Lower	Climb" ,
 "First Aid" ,
 "Geology" ,
 "History" ,
 "Jump" ,
 "Natural History" ,
 "Navigate" ,
 "Spot Hidden", "STR=1" ,
 "CON=1	Local Residents"},

{"Race Driver",	1920	,"Upper Lower-Upper	Drive Auto" ,
 "Electrical Repair" ,
 "Mechanical Repair" ,
 "Pilot Boat" ,
 "Psychology" ,
 "Spot Hidden	", "Auto Manufacturers" ,
 "Boat Manufacturers" ,
 "Film Industry Practiced drivers and pilots can pull off certain stunts with their machines, even crashing or rolling an automobile with comparative control and safety."},

{"Treasure Hunter",	1920	,"Pauper+",
"Bargain" ,
 "Climb" ,
 "Drive Auto" ,
 "Electrical Repair" ,
 "History" ,
 "Jump" ,
 "Mechanical Repair" ,
 "Persuade" ,
 "Pilot Aircraft" ,
 "Pilot Boat" ,
 "Spot Hidden	","Spot Hidden+20", "Investors" ,
 "Treasure Hunters" ,
 "Local Government" ,
 "Foreign Government" ,
 "Coast Guard" ,
 "Local Law Officials"},

{"Architect", "Lower Middle-Upper Middle",
	"Accounting" ,
 "Art" ,
 "Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Library Use" ,
 "Persuade" ,
 "Psychology" ,
 "Architectural History", "?opt:Skill=`Architectural History`" ,
 "Skill Bonus=rand(20)+40	Local Building/City Engineering Departments" ,
 "Construction Firms"},

{"Designer", "Lower Middle-Upper Middle",
	"Accounting" ,
 "Art" ,
 "Craft" ,
 "Bargain" ,
 "Electrical Repair" ,
 "Mechanical Repair" ,
 "Photography" ,
 "Psychology	", "Advertising Industry" ,
 "Stage Contacts" ,
 "Furnishings Industry" ,
 "Architects"},

{"Painter/Sculptor", "Lower Middle-Middle	Art" ,
 "Bargain" ,
 "History" ,
 "Library Use" ,
 "Persuade" ,
 "Photography" ,
 "Psychology" ,
 "Art History", "?opt:Skill=`Art History`" ,
 "Skill Bonus=rand(20)+40	Art Galleries" ,
 "Art Critics" ,
 "Monied Patrons" ,
 "Advertising Industry"},

{"Photographer", "Lower Middle-Middle",
	"Accounting" ,
 "Chemistry" ,
 "Photography" ,
 "Persuade" ,
 "Physics" ,
 "Psychology" ,
 "Dark Room	", "Advertising Industry" ,
 "News Industry" ,
 "Film Industry" ,
 "Film Manufacturers" ,
 "Camera Manufacturers	Special emulsions capable of capturing invisible or alien creatures on film might be developed if successful Chemistry rolls are made."},

{"Writer", "Lower Middle+", "Art" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Library Use" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade" ,
 "Psychology" ,
 "Literature History", "?opt:Skill=`Literature History`" ,
 "Skill Bonus=rand(20)+20	Libraries" ,
 "Writers" ,
 "Publishing Industry" ,
 "Advertising Industry" ,
 "Film Industry"},

{"Entertainer, Performance", "Upper Lower-Lower Middle",
"Art" ,
 "Disguise" ,
 "English" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology","APP=1" ,
 "?setval:Choose Bonus,_bonus,+1 DEX,+50% to Entertainment Skill" ,
 "?if:_bonus=+1 DEX",
 "DEX=1" ,
 "?else" ,
 "?seloptval:Skill=Choose Entertainment Skill,*Skills:Art" ,
 "Skill Bonus=50" ,
 "?clearopt" ,
 "?cat:Skills" ,
 "?list:Skills" ,
 "@@optValue(`Bonuses`, `Skill Bonus`, `Skill`)@@" ,
 "?endif Vaudeville" ,
 "Broadway Stage" ,
 "Film Industry" ,
 "Entertainment Critics" ,
 "Organized Crime"},

{"Film Crew",	1920	,"Lower Middle",
"Art" ,
 "Climb" ,
 "Drive Auto" ,
 "Electrical Repair" ,
 "Mechanical Repair" ,
 "Photography	", "Film Industry" ,
 "Film Unions"},

{"Film Star",	1920	,"Pauper-Wealthy	Art" ,
 "Bargain" ,
 "Disguise" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Persuade" ,
 "Psychology", "APP=1	Film Industry" ,
 "Newspaper Critics" ,
 "Organized Crime" ,
 "Actor`s Guild"},

{"Musician, Legitimate", "Lower Middle",
"Accounting" ,
 "Art" ,
 "Bargain" ,
 "Listen" ,
 "Persuade" ,
 "Psychology	", "Musicians" ,
 "Musician`s Union" ,
 "Monied Patrons"},

{"Stage Actor", "Upper Lower-Lower Middle",
"Art" ,
 "Disguise" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Persuade" ,
 "Psychology", "APP=1	Theatre Industry" ,
 "Newspaper Critics" ,
 "Actor`s Guild	Actors are skilled at disguising their emotions (when they wish to) and are difficult to analyze with Psychology. Lies and hidden motivations escape detection as the actor weaves a false reality for himself and others."},

{"Stage Hand", "Pauper-Upper Lower",
"Art" ,
 "Craft" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Disguise" ,
 "Persuade" ,
 "Psychology	", "Theatre Industry" ,
 "Actor`s Guild"},

{"Stunt Man",	1920	,"Upper Lower",
"Climb" ,
 "Disguise" ,
 "Dodge" ,
 "Drive Auto" ,
 "Electrical Repair" ,
 "First Aid" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Jump" ,
 "Kick" ,
 "Mechanical Repair" ,
 "Pilot Aircraft" ,
 "Pilot Boat" ,
 "Swim" ,
 "Throw", "CON=1" ,
 "DEX=1	Film Industry" ,
 "Explosive and Pyrotechnic Firms" ,
 "Free Lance Inventors"},

{"Talent Agent",	1920	,"Lower+",
	"Accounting" ,
 "Bargain" ,
 "Fast Talk" ,
 "Law" ,
 "Persuade" ,
 "Psychology	", "Publishing Industry" ,
 "Film Industry	Impervious to most Fast Talk"},

{"Acrobat", "Lower-Lower Middle",
"Bargain" ,
 "Climb" ,
 "Dodge" ,
 "Jump" ,
 "Choose:Other Language,1,*Language" ,
 "Throw","?setval:Choose Bonus,_bonus,+2 DEX,+1 STR and +1 DEX" ,
 "?if:_bonus= +2 DEX",
 "DEX=2" ,
 "?else" ,
 "DEX=1" ,
 "STR=1" ,
 "?endif Amateur Athletic Circles" ,
 "Sports Writers" ,
 "Circuses" ,
 "Carnivals"},

{"Boxer/Wrestler", "Lower-Lower Middle",
"Fist/Punch" ,
 "Grapple" ,
 "Dodge" ,
 "Head Butt" ,
 "Kick" ,
 "Throw", "CON=2" ,
 "STR=1" ,
 "EDU=-2	Boxing Promoters" ,
 "Sports Writers" ,
 "Organized Crime"},

{"Golf Pro",	1920	,"Middle-Upper Middle",
"Bargain" ,
 "Club[Club (golf)]" ,
 "Credit Rating" ,
 "Persuade" ,
 "Psychology" ,
 "Spot Hidden", "CON=1" ,
 "EDU=-2	Sports Writers" ,
 "Golf Pros" ,
 "Wealthy / Influential Club Members"},

{"Professional Sports Athlete",	1920	,"Lower-Lower Middle+", "Block" ,
 "Club" ,
 "Dodge" ,
 "Grapple" ,
 "Head Butt" ,
 "Jump" ,
 "Kick" ,
 "Spot Hidden" ,
 "Throw", "CON=1" ,
 "Choose Bonus,1-1,STR=1,SIZ=1,DEX=1,Move=1" ,
 "EDU=-2	Sports Personalities" ,
 "Sports Writers" ,
 "Gamblers"},

{"Manager/Coach",	1920	,"Upper Lower-Upper Middle", 
"Accounting" ,
 "Block" ,
 "Bargain" ,
 "Dodge" ,
 "Fast Talk" ,
 "First Aid" ,
 "Head Butt" ,
 "Kick" ,
 "Persuade" ,
 "Psychology", "SIZ=1	Athletic Circles" ,
 "Sports Writers" ,
 "Wealthy / Influential Alumnae"},

{"Swimmer/Diver", "Pauper	Choose:Other Language,1,*Language" ,
 "Swim", "CON=1	Amateur Athletic Circles" ,
 "Sports Writers	+1 to Swimming movement. Unless conditions dictate otherwise (freezing temperatures, strong currents, undertow, waves, etc.), accomplished swimmers are nearly impervious to drowning, capable of treading water nearly effortlessly for hours.", "+1 Swim"},

{"Tennis Pro",	1920	,"Lower Middle-Upper Middle",
"Bargain" ,
 "Club[Club (tennis racket)]" ,
 "Credit Rating" ,
 "Dodge" ,
 "Jump" ,
 "Persuade" ,
 "Psychology" ,
 "Spot Hidden", "CON=1" ,
 "DEX=1" ,
 "EDU=-2	Tennis Pros" ,
 "Sports Writers" ,
 "Wealthy / Influential Club Members	A good build and a fine tan can add as much as +2 to APP, particularly when dealing with members of the opposite sex."},

{"Track and Field", "Pauper	Climb" ,
 "Dodge" ,
 "Jump" ,
 "Choose:Other Language,1,*Language" ,
 "Throw", "CON=1" ,
 "Choose Bonus,1-1,STR=1,Move=1	Amateur Athletic Circles" ,
 "Sports Writers"},

{"Trainer",	1920	,"Lower-Upper Lower",
"Fast Talk" ,
 "Sports Medicine" ,
 "First Aid" ,
 "Medicine" ,
 "Persuade" ,
 "Pharmacy" ,
 "Psychology", "?opt:Skill=`Sports Medicine`" ,
 "Skill Bonus=rand(20)+40	Athletic Circles" ,
 "Medical Professionals	Sports Medicine can be used to splint, brace, or otherwise repair an injured limb so that it remains at least semi-functional. This can be used to put an investigator with a sprained ankle temporarily back on his feet."},

{"Accountant", "Upper Lower-Middle",
	"Accounting" ,
 "Credit Rating	", "Accountants"},

{"Barber", "Upper Lower-Lower Middle",
"Accounting" ,
 "Straight Razor" ,
 "Bargain" ,
 "Credit Rating" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology	", "Local Residents"},

{"Clerk", "Upper Lower-Lower Middle",
"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Persuade" ,
 "Psychology	", "Office Workers"},

{"Company Officer", "Upper Middle-Wealthy",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+35", "Business World" ,
 "Finance World" ,
 "College Connections" ,
 "Masons or other Fraternal Groups" ,
 "Local Government" ,
 "Federal Government" ,
 "News Industry" ,
 "Magazine Industry"},

{"Executive", "Upper Middle-Wealthy",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+20", "Business World" ,
 "Finance World" ,
 "College Connections" ,
 "Masons or other Fraternal Groups" ,
 "Local Government" ,
 "Federal Government" ,
 "News Industry" ,
 "Magazine Industry"},

{"Salesman", "Lower Middle-Upper Middle",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology	", "Business World	Salesmen are nearly impervious to Fast Talk or Persuade, and Psychology usually reveals little about them other than a desire to sell their product or service. Once the salesman is better known to a person, Psychology is more effective."},

{"Secretary",	1920	,"Upper Lower-Middle",	"Accounting" ,
 "Typing" ,
 "Shorthand" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Persuade" ,
 "Psychology	", "Office Workers	Special skills include such things as Typing and Shorthand, the latter of particular use in certain situations."},

{"Shopkeeper", "Upper Lower-Middle",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+20", "Local Residents" ,
 "Local Law Officials" ,
 "Local Government"},

{"Small Business Owner", "Middle-Upper",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+20	?seloptval:Skill=Choose Business Skill,*Skills" ,
 "Skill Bonus=30" ,
 "?clearopt" ,
 "?cat:Skills" ,
 "?list:Skills" ,
 "@@optValue(`Bonuses`, `Skill Bonus`, `Skill`)@@	Customers" ,
 "Bankers" ,
 "Suppliers"},

{"Stock Broker",	1920	,"Upper Middle-Wealthy",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+30", "Business World" ,
 "Finance World" ,
 "Investors"},

{"Switchboard Operator",	1920	,"Upper Lower-Lower Middle",
"Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Listen" ,
 "Persuade" ,
 "Psychology	", "Office Workers	Operators can listen in on phone calls at will. They usually know more of the intimate details of a  corporation or office than anyone else."},

{"Travelling Salesman", "Upper Lower-Lower Middle",
"Accounting" ,
 "Bargain" ,
 "Drive Auto" ,
 "Fast Talk" ,
 "Navigate" ,
 "Persuade" ,
 "Psychology", "CON=1", "Traveling salesmen are generally impervious to Fast Talk and Persuade. Psychology is mostly ineffective, unless the salesman is well-known to the person."},

{"Bible Salesman", "Lower-Upper Lower",
"Accounting" ,
 "Bargain" ,
 "Persuade" ,
 "Psychology", "CON=1	Religious Publishers"},

{"Catholic Priest", "Upper Lower-Upper Middle", 
"",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Latin" ,
 "Library Use" ,
 "Occult" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+20", "Church Hierarchy" ,
 "Local Congregation" ,
 "Community Leaders	Priests bear witness to confessions and though they are not at liberty to divulge such secrets, they are free to act upon them."},

{"Charismatic Cult Leader", "Upper Lower-Upper Middle", 
"",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology", "APP=1	Movie Stars" ,
 "Rich Widows"},

{"Deacon/Elder", "Unpaid",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+10", "Church Hierarchy" ,
 "Local Congregation" ,
 "Local Businesses" ,
 "Community Leaders"},

{"Itinerant Preacher", "Pauper-Lower	Bargain" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Hide" ,
 "Persuade" ,
 "Psychology" ,
 "Sneak", "SAN=-20	God	Most suffer a penalty of minus 20 sanity points from beginning current sanity but, being half-mad already, are usually impervious to the effects of temporary insanity - although they lose sanity points as normal."},

{"Missionary 20th C",	1920	,"Pauper-Lower Middle",
"Anthropology" ,
 "Bargain" ,
 
 "Choose:Own Language,1,*Language" ,

 "Occult" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade" ,
 "Psychology", "CON=1	Church Hierarchy" ,
 "Foreign Government"},

{"Protestant Minister", "Lower Middle-Upper Middle",
	"Accounting" ,
 "Bargain" ,
 
 "Choose:Own Language,1,*Language" ,

 "Library Use" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+10", "Church Hierarchy" ,
 "Local Congregation" ,
 "Community Leaders"},

{"Rabbi", "Lower-Upper Middle",
"Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Hebrew" ,
 "History" ,
 "Library Use" ,
 "Occult" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+30", "Jewish Scholars" ,
 "Local Jewish Community"},

{"Bank Robber", "Lower-Upper Middle",
"Club" ,
 "Conceal" ,
 "Drive Auto" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Kick" ,
 "Knife", "EDU=-6" ,
 "SAN=-(10+rand(6))	Gang Members" ,
 "Friends and Family of Gang Members" ,
 "Local Residents"},

{"Bookie", "Middle-Upper",
	"Accounting" ,
 "Bargain" ,
 "Conceal" ,
 "Credit Rating" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology", "EDU=-2	Organized Crime" ,
 "Gamblers" ,
 "Police" ,
 "Sports Personalities"},

{"Bootlegger/Thug", "Upper Lower-Middle	Club" ,
 "Conceal" ,
 "Drive Auto" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Kick" ,
 "Knife", "EDU=-6	Organized Crime" ,
 "Street Scene" ,
 "Police" ,
 "Local Ethnic Community"},

{"Burglar", "Lower-Lower Middle",
"Conceal" ,
 "Climb" ,
 "Hide" ,
 "Jump" ,
 "Listen" ,
 "Locksmith" ,
 "Sneak" ,
 "Spot Hidden	","Spot Hidden+20	EDU=-4	Fences" ,
 "Burglars"},

{"Con Man", "Lower-Lower Middle",
"Bargain" ,
 "Disguise" ,
 "Fast Talk" ,
 "Listen" ,
 "Persuade" ,
 "Psychology" ,
 "Spot Hidden	", "Con Men	Immune to Fast Talk and Persuade" ,
 " even Psychology is ineffective unless the user knows the con man well."},

{"Fence", "Lower Middle-Upper Middle",
	"Accounting" ,
 "Bargain" ,
 "Conceal" ,
 "Credit Rating" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology", "EDU=-4	Street  Criminals" ,
 "Organized Crime" ,
 "Police" ,
 "Local Businesses"},

{"Forger/Counterfeiter", "Upper Lower-Upper Middle", 
"",
	"Accounting" ,
 "Engraving" ,
 "Drawing" ,
 "Art" ,
 "Bargain" ,
 "Conceal" ,
 "Craft" ,
 "Spot Hidden" ,
 "Persuade" ,
 "Psychology	", "Organized Crime" ,
 "Street  Criminals" ,
 "Businessmen	Knowledge of inks, paper, printing processes, etc."},

{"Gambler", "Lower-Upper Middle",
"Accounting" ,
 "Bargain" ,
 "Conceal" ,
 "Fast Talk" ,
 "Listen" ,
 "Persuade" ,
 "Psychology" ,
 "Spot Hidden", "Luck=10	Bookies" ,
 "Organized Crime" ,
 "Street Scene"},

{"Gangster", "Middle-Wealthy	Bargain" ,
 "Club" ,
 "Conceal" ,
 "Drive Auto" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Kick" ,
 "Knife" ,
 "Persuade" ,
 "Psychology", "EDU=-6" ,
 "SAN=-(10+rand(6))	Organized Crime" ,
 "Unions" ,
 "Street Scene" ,
 "Police" ,
 "Local Government" ,
 "Politicians" ,
 "Judges" ,
 "District Attorneys" ,
 "Local Ethnic Community" ,
 "Local Church	Most gangsters are immune to sanity losses resulting from witnessing a murder, viewing a corpse, or seeing violence perpetrated against a human being. Gangsters also harbor a secret phobia to be chosen by the keeper and exposed when the investigator least expects it. American-born Italian gangsters begin with 1D20+20 points in Italian."},

{"Gangster, Mafia", "Middle-Wealthy	Bargain" ,
 "Club" ,
 "Conceal" ,
 "Drive Auto" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Kick" ,
 "Knife" ,
 "Persuade" ,
 "Psychology" ,
 "Italian", "?opt:Skill=`Italian`" ,
 "Skill Bonus=rand(20)+20" ,
 "?clearopt" ,
 "EDU=-6" ,
 "SAN=-(10+rand(6))	Organized Crime" ,
 "Unions" ,
 "Street Scene" ,
 "Police" ,
 "Local Government" ,
 "Politicians" ,
 "Judges" ,
 "District Attorneys" ,
 "Local Ethnic Community" ,
 "Local Church	Most gangsters are immune to sanity losses resulting from witnessing a murder, viewing a corpse, or seeing violence perpetrated against a human being. Gangsters also harbor a secret phobia to be chosen by the keeper and exposed when the investigator least expects it. American-born Italian gangsters begin with 1D20+20 points in Italian."},

{"Hit Man", "Upper Lower-Upper Middle", 
"	Bargain" ,
 "Club" ,
 "Conceal" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Kick" ,
 "Knife" ,
 "Sneak" ,
 "Hide", "EDU=-6" ,
 "SAN=-(20+rand(6))	Underworld	Hit men harbor 1D2 secret phobias."},

{"Hooker", "Lower-Upper Middle",
"Bargain" ,
 "Conceal" ,
 "Fast Talk" ,
 "Hide" ,
 "Persuade" ,
 "Psychology", "APP=1" ,
 "EDU=-2	Street Scene" ,
 "Police" ,
 "Organized Crime" ,
 "Customers"},

{"Loan Shark", "Middle-Upper",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology", "EDU=-2	Organized Crime" ,
 "Gamblers" ,
 "Police" ,
 "Debtors"},

{"Pick Pocket", "Lower-Upper Lower",
"Conceal" ,
 "Fast Talk" ,
 "Hide" ,
 "Listen" ,
 "Sneak" ,
 "Spot Hidden", "EDU=-4	Street Scene" ,
 "Police"},

{"Punk", "Pauper-Lower	Club" ,
 "Pick Pocket" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Kick" ,
 "Knife" ,
 "Throw", "EDU=-6	Street  Criminals" ,
 "Gangsters" ,
 "Punks" ,
 "Fences" ,
 "Police"},

{"Shifty Accountant/Lawyer", "Middle-Upper Middle",
"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Law" ,
 "Persuade" ,
 "Psychology	", "Organized Crime" ,
 "Finance World" ,
 "District Attorneys" ,
 "Judges	Due to your position, you can usually lay your hands on large amounts of money - although skimming is a risky business."},

{"Smuggler", "Lower Middle-Upper Middle",
	"Accounting" ,
 "Bargain" ,
 "Conceal" ,
 "Fast Talk" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Listen" ,
 "Navigate" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade" ,
 "Pilot Aircraft" ,
 "Pilot Boat" ,
 "Psychology" ,
 "Spot Hidden	", "Organized Crime" ,
 "Coast Guard" ,
 "U.S. Customs"},

{"Spy", "Lower Middle-Upper Middle",
	"Bargain" ,
 "Disguise" ,
 "Fast Talk" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Hide" ,
 "Knife" ,
 "Listen" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade" ,
 "Psychology" ,
 "Sneak" ,
 "Spot Hidden	", "Safe House	Although exceptions to the rule might arise, spies are generally immune to Fast Talk, Persuade and Psychology."},

{"Columnist",	1920	,"Lower Middle-Upper Middle",
"Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Persuade" ,
 "Psychology	", "News Industry"},

{"Copywriter",	1920	,"Upper Lower-Middle",	"?opt:Native=1" ,
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Listen" ,
 "Persuade" ,
 "Psychology	", "News Industry"},

{"Editor",	1920	,"Lower Middle-Upper Middle",
"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Persuade" ,
 "Psychology	", "News Industry" ,
 "Local Government"},

{"Foreign Correspondent",	1920	,"Lower Middle-Upper Middle",
"Bargain" ,
 "Conceal" ,
 "Fast Talk" ,
 "Hide" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade" ,
 "Psychology" ,
 "Sneak	", "News Industry" ,
 "Military" ,
 "Foreign Government	Veteran journalists who have covered violent events may avoid sanity losses due to human death or maiming. War corresondents enjoy similar immunity. Keepers must judge the circumstances depending on the journalist`s precise background."},

{"Photojournalist",	1920	,"Lower Middle-Middle	Climb" ,
 "Bargain" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Jump" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade" ,
 "Psychology" ,
 "Photography	", "News Industry" ,
 "Film Manufacturers" ,
 "Camera Manufacturers"},

{"Radio Announcer",	1920	,"Middle-Upper	Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Persuade" ,
 "Psychology	", "News Industry" ,
 "Hollywood" ,
 "Radio Industry"},

{"Reporter",	1920	,"Upper Lower-Middle",	"Bargain" ,
 "Climb" ,
 "Conceal" ,
 "Disguise" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Hide" ,
 "Jump" ,
 "Listen" ,
 "Persuade" ,
 "Psychology" ,
 "Sneak" ,
 "Spot Hidden	", "News Industry" ,
 "High Society" ,
 "Local Government" ,
 "Politicians" ,
 "Finance World" ,
 "Sports Professionals" ,
 "Police" ,
 "Organized Crime" ,
 "Street Scene	Depending upon the beat the reporter covers, he may have grown calloused to the sight of human violence and suffering and may suffer reduced or negated sanity losses for witnessing such things."},

{"Farmer/Farm Hand", "Upper Lower-Lower Middle",
"Accounting" ,
 "Drive Auto[Drive Auto/Tractor]" ,
 "Medicine[Medicine (veterinary)]" ,
 "Axe" ,
 "Bargain" ,
 "Climb" ,
 "Craft" ,
 "Credit Rating" ,
 "Electrical Repair" ,
 "First Aid" ,
 "Jump" ,
 "Mechanical Repair" ,
 "Natural History" ,
 "Operate Heavy Machine	","Skills:Credit Rating+20	CON=1" ,
 "STR=1	Bankers" ,
 "State Agricultural Department" ,
 "Local Government	Add 20 points to Credit Rating if you own your farm."},

{"Lumberjack", "Upper Lower",
"Axe" ,
 "French" ,
 "Bargain" ,
 "Block" ,
 "Climb" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Kick" ,
 "Jump	","Skills:French+20	STR=1" ,
 "CON=1" ,
 "EDU=-2"},

{"Miner", "Upper Lower",
"Climb" ,
 "Geology" ,
 "Jump" ,
 "Operate Heavy Machine" ,
 "Spot Hidden	","Spot Hidden+20	STR=1" ,
 "CON=-1" ,
 "EDU=-2	Unions	Miners are generally immune to claustrophobia and have a faster than normal crawling speed. Special skills include some knowledge of mine engineering, rigging ropes and braces, and digging and tunneling equipment."},

{"Ranch Hand/Cowboy", "Lower-Lower Middle",
"Accounting" ,
 "Bargain" ,
 "Craft" ,
 "Credit Rating" ,
 "Drive Auto" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "First Aid" ,
 "Jump" ,
 "Medicine[Medicine (veterinary)]" ,
 "Natural History" ,
 "Ride	","Skills:Credit Rating+20	CON=1" ,
 "STR=1	Bankers" ,
 "Local Government" ,
 "State Agricultural Department	Add 20 points to Credit Rating if you own your own spread."},

{"Bartender", "Upper Lower-Lower Middle",
"Accounting" ,
 "Club" ,
 "Fast Talk" ,
 "Fist/Punch" ,
 "Persuade" ,
 "Psychology", "EDU=-2	Customers" ,
 "Organized Crime"},

{"Bus Driver/Streetcar Conductor",	1920	,"Lower Middle",
"Accounting" ,
 "Drive Auto[Drive Auto/Bus]" ,
 "Electrical Repair" ,
 "Mechanical Repair" ,
 "Navigate" ,
 "Persuade" ,
 "Psychology", "EDU=-2	Customers"},

{"Cocktail Waitress", "Upper Lower-Lower Middle",
"Accounting" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology", "APP=1" ,
 "EDU=-2	Customers" ,
 "Organized Crime"},

{"Laborer",	1920	,"Upper Lower",
"Operate Heavy Machine", "EDU=-2" ,
 "Choose Bonus,1-1,STR=1,CON=1"},

{"Skilled Trade/Mechanic",	1920	,"Lower Middle",
"Climb" ,
 "Craft[Craft (carpentry, plumbing, etc.)]" ,
 "Electrical Repair" ,
 "Mechanical Repair" ,
 "Operate Heavy Machine", "Choose Bonus,1-1,STR=1,CON=1	Unions"},

{"Taxi Driver",	1920	,"Lower-Upper Lower",
"Accounting" ,
 "Bargain" ,
 "Drive Auto" ,
 "Electrical Repair" ,
 "Fast Talk" ,
 "Mechanical Repair" ,
 "Navigate" ,
 "Persuade" ,
 "Psychology", "EDU=-2	Street Scene" ,
 "Customers"},

{"Union Activist", "Pauper",
	"Accounting" ,
 "Bargain" ,
 "Club" ,
 "Conceal" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Kick" ,
 "Law" ,
 "Operate Heavy Machine" ,
 "Persuade" ,
 "Psychology	", "Unions" ,
 "Socialists" ,
 "Subversives" ,
 "Communists" ,
 "Organized Crime"},

{"Agency Detective", "Lower Middle-Middle	Bargain" ,
 "Fast Talk" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Handgun" ,
 "Hide" ,
 "Law" ,
 "Library Use" ,
 "Persuade" ,
 "Psychology" ,
 "Sneak" ,
 "Track	", "Police" ,
 "Previous Clients	Immunity to sanity losses from corpses, injuries, etc."},

{"Bounty Hunter", "Upper Lower-Lower Middle",
"Accounting" ,
 "Bargain" ,
 "Climb" ,
 "Drive Auto" ,
 "Electrical Repair" ,
 "Fast Talk" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Hide" ,
 "Jump" ,
 "Kick" ,
 "Law" ,
 "Persuade" ,
 "Psychology" ,
 "Sneak", "STR=1" ,
 "SIZ=1	Police" ,
 "Bail Bondsmen	Although violence and criminals are all part of his work, the bounty hunter is rarely exposed to murder or maiming. In most instances they suffer normal sanity losses."},

{"Federal Agents", "Lower Middle-Upper Middle",
	"Bargain" ,
 "Drive Auto" ,
 "Fast Talk" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Hide" ,
 "Law" ,
 "Persuade" ,
 "Sneak" ,
 "Spot Hidden" ,
 "Track	", "Federal Government" ,
 "Organized Crime	As with other law enforcement occupations, past exposure to death and injury often reduces or eliminates sanity losses."},

{"Forensic Specialist", "Lower Middle-Middle	Biology" ,
 "Chemistry" ,
 "Law" ,
 "Medicine" ,
 "Pharmacy" ,
 "Photography" ,
 "Spot Hidden	", "Local Labs" ,
 "Law Enforcement" ,
 "Chemical Suppliers	Immune to sanity losses due to viewing most muder or injury scenes."},

{"Plainclothes Detective", "Lower Middle-Middle	Bargain" ,
 "Drive Auto" ,
 "Fast Talk" ,
 "Handgun" ,
 "Law" ,
 "Listen" ,
 "Persuade" ,
 "Psychology" ,
 "Spot Hidden" ,
 "Track	", "Coroner`s Office" ,
 "Law Enforcement" ,
 "Street Scene" ,
 "Organized Crime	Immune to sanity losses resulting from the sight of normal corpses or injuries. Immune to most Fast Talk and Persuade attempts."},

{"Private Eye", "Upper Lower-Lower Middle",
"Bargain" ,
 "Accounting" ,
 "Climb" ,
 "Disguise" ,
 "Drive Auto" ,
 "Fast Talk" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Hide" ,
 "Jump" ,
 "Law" ,
 "Library Use" ,
 "Persuade" ,
 "Sneak" ,
 "Swim" ,
 "Track	", "Law Enforcement" ,
 "Newspaper Morgues" ,
 "Criminals" ,
 "Office Workers	Lowered or negated sanity losses when viewing murder victims, gross injuries, etc."},

{"Uniformed Police Officer", "Lower Middle-Middle	Club" ,
 "Drive Auto" ,
 "Fist/Punch" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Grapple" ,
 "Kick" ,
 "Law" ,
 "Persuade" ,
 "Track", "?seloptval:Skill=Select Combat Skill at 50%,*Skills:Combat" ,
 "Skill Bonus=50" ,
 "?clearopt" ,
 "STR=1" ,
 "SIZ=1	Law Enforcement" ,
 "Local Businesses" ,
 "Street Scene" ,
 "Organized Crime	Officers on the street are used to a certain level of violence and murder scenes or the sight of gross injuries are unlikely to result in sanity losses."},

{"Western Lawman", "Upper Lower-Lower Middle",
"Drive Auto" ,
 "Rope" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Kick" ,
 "Law" ,
 "Persuade" ,
 "Psychology" ,
 "Ride" ,
 "Track	","Skills:Firearms+50", "Local Law Officials" ,
 "Local Residents" ,
 "Street  Criminals	Resistant to sanity losses resulting from witnessing murder, human violence, or normal injury."},

{"Bail Bondsman", "Middle-Upper",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 "Fast Talk" ,
 "Law" ,
 "Persuade" ,
 "Psychology	", "Street Scene" ,
 "Bounty Hunters" ,
 "Courts" ,
 "Organized Crime"},

{"Judge", "Middle-Upper	Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Law" ,
 "Library Use" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+40", "Legal Connections" ,
 "Organized Crime"},

{"Practicing Attorney", "Lower Middle-Upper",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Law" ,
 "Library Use" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+20", "Legal Connections" ,
 "Criminals"},

{"Prosecuting Attorney", "Lower Middle-Upper Middle",
	"Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Law" ,
 "Library Use" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+30", "Legal Connections" ,
 "Organized Crime"},

{"Dentist", "Lower Middle-Upper Middle",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 "First Aid" ,
 "Library Use" ,
 "Medicine" ,
 "Persuade" ,
 "Pharmacy" ,
 "Psychology	","Skills:Credit Rating+10", "Previous Clients	You have ready access to special gases and anesthetics."},

{"Forensic Surgeon",	1920	,"Middle-Upper Middle",
"Biology" ,
 "Forensic Surgery" ,
 "Credit Rating" ,
 "First Aid" ,
 "Library Use" ,
 "Medicine" ,
 "Pharmacy	","Skills:Credit Rating+20", "Local Labs" ,
 "Law Enforcement" ,
 "Medical Professionals	Immune to sanity losses caused by gore and/or bad smells."},

{"Nurse", "Lower Middle-Middle	Biology" ,
 "Credit Rating" ,
 "First Aid" ,
 "Medicine" ,
 "Persuade" ,
 "Psychology" ,
 "Pharmacy	","Skills:Credit Rating+10", "Nurses share an immunity similar to physicians regarding certain sanity losses. They also have access to drugs, equipment and medical records."},

{"Orderly",	1920	,"Upper Lower",
"Electrical Repair" ,
 "Fast Talk" ,
 "First Aid" ,
 "Hide" ,
 "Mechanical Repair" ,
 "Sneak", "EDU=-2	Medical supplies, drugs, records"},

{"Pharmacist", "Middle-Upper Middle",
"Accounting" ,
 "Bargain" ,
 "Biology" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "First Aid" ,
 "Latin" ,
 "Library Use" ,
 "Pharmacy" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+10", "Medical Professionals" ,
 "Local Residents"},

{"Physician", "Middle-Upper",
	"Accounting" ,
 "Bargain" ,
 "Biology" ,
 "Credit Rating" ,
 "First Aid" ,
 "Latin" ,
 "Library Use" ,
 "Medicine" ,
 "Persuade" ,
 "Pharmacy" ,
 "Psychoanalysis" ,
 "Psychology	","Skills:Credit Rating+30", "Local Residents	Due to the nature of the work, physicians may be immune to some sanity losses caused by injury and death. Medical examiners are particularly resistant to these sorts of losses. A physiscian has high community status, and might be able to talk his way past many standard hospital regulations, obtaining evidence not readily available to others."},

{"Plastic Surgeon",	1920	,"Middle-Upper Middle",
"Accounting" ,
 "Bargain" ,
 "Biology" ,
 "Credit Rating" ,
 "First Aid" ,
 "Latin" ,
 "Library Use" ,
 "Medicine" ,
 "Pharmacy" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+20", "Medical Professionals" ,
 "Hollywood" ,
 "Criminals"},

{"Technician",	1920	,"Lower Middle-Middle	Biology" ,
 "Chemistry" ,
 "Electrical Repair" ,
 "Library Use" ,
 "Mechanical Repair" ,
 "Medicine" ,
 "Pharmacy" ,
 "Photography	","Skills:Credit Rating+10", "Medical supplies, drugs, records"},

{"Alienist", "Lower Middle-Middle",
	"Accounting" ,
 "Bargain" ,
 "Biology" ,
 "Fast Talk" ,
 "Library Use" ,
 "Medicine" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade" ,
 "Pharmacy" ,
 "Psychoanalysis" ,
 "Psychology	", "Psychological Community	A trained psychoanalyst can use his techniques to negate the effects of his own temporary insanity. Successful negation requires a Psychoanalysis roll. Regardless of the outcome, the sanity point losses still apply."},

{"Madhouse Attendant", "Upper Lower",
"Club" ,
 "Fast Talk" ,
 "First Aid" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Kick" ,
 "Listen" ,
 "Persuade" ,
 "Psychology" ,
 "Sneak", "STR=1" ,
 "SIZ=1" ,
 "EDU=-2	Medical supplies, drugs, records"},

{"Psychologist", "Lower Middle-Middle",
	"Accounting" ,
 "Bargain" ,
 "Library Use" ,
 "Persuade" ,
 "Psychoanalysis" ,
 "Psychology	", "Psychological Community"},

{"Mercenary", "Lower Middle-Middle	Bargain" ,
 "Bayonet" ,
 "Climb" ,
 "Club" ,
 "Fist/Punch" ,
 "Handgun" ,
 "Rifle" ,
 "Shotgun" ,
 "Submachine Gun" ,
 "Machine Gun" ,
 "Garrote" ,
 "Grapple" ,
 "Head Butt" ,
 "Hide" ,
 "Jump" ,
 "Kick" ,
 "Knife" ,
 "Navigate" ,
 "Track" ,
 "Sneak" ,
 "Swim", "?seloptval:Skill=Choose Combat or Weapon Skill,*Skills:Combat" ,
 "Skill Bonus=100" ,
 "?clearopt" ,
 "?cat:Skills" ,
 "?list:Skills" ,
 "@@optValue(`Bonuses`, `Skill Bonus`, `Skill`)@@	Mercenary Networks" ,
 "Illegal Arms Dealers" ,
 "Small Governments" ,
 "Multinational Corporations"},

{"Military Officer 20th C",	1920	,"Upper Lower-Upper Middle", 
"	Bargain" ,
 "Credit Rating" ,
 "Dodge" ,
 "Fast Talk" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Handgun" ,
 "Head Butt" ,
 "Hide" ,
 "Jump" ,
 "Kick" ,
 "Navigate" ,
 "Persuade" ,
 "Psychology" ,
 "Sneak	","Skills:Credit Rating+10"	,"EDU=1	Military" ,
 "Federal Government	Veterans of the World War are immune to sanity losses stemming from dead bodies, gross injuries, etc. However, such characters suffer from a secret phobia."},

{"Sailor", "Upper Lower-Middle	Climb" ,
 "Artillery" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Handgun" ,
 "Head Butt" ,
 "Jump" ,
 "Kick" ,
 "Navigate" ,
 "Rifle" ,
 "Swim" ,
 "Accounting" ,
 "Mechanical Repair" ,
 "Operate Heavy Machine", "EDU=-2	Military" ,
 "Veteran`s Administration",	"Sailors saw less action than other servicement. Only those that can `verify` exposure to the agonies of war can claim immunity to sanity losses like other veterans."},

{"Soldier/Marine", "Upper Lower-Middle	Bayonet" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Head Butt" ,
 "Kick" ,
 "Knife" ,
 "Rifle" ,
 "Throw" ,
 "Artillery" ,
 "Drive Auto[Drive Tank]" ,
 "Electrical Repair" ,
 "Mechanical Repair" ,
 "Medicine", "EDU=-2" ,
 "?seloptval:Skill=Choose Combat or Weapon Skill,*Skills:Combat" ,
 "Skill Bonus=50" ,
 "?clearopt" ,
 "?cat:Skills" ,
 "?list:Skills" ,
 "@@optValue(`Bonuses`, `Skill Bonus`, `Skill`)@@	Military" ,
 "Veteran`s Administration	Soldier and Marine war veterans are immune to some sanity losses, but suffer from a secret phobia. Upon death they are entitled to a free head stone courtesy of the U.S. government."},

{"Ambassador", "Upper	Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade	","Skills:Credit Rating+30","APP=1	Federal Government" ,
 "News Industry" ,
 "Foreign Government"},

{"Boss", "Upper Middle-Wealthy",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology	","Skills:Credit Rating+20", "News Industry" ,
 "Finance World" ,
 "Organized Crime" ,
 "Business World"},

{"Communist/Radical", "Unpaid	Club" ,
 "Fast Talk" ,
 "Fist/Punch" ,
 "Grapple" ,
 "Handgun" ,
 "Head Butt" ,
 "Kick" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade" ,
 "Psychology	", "Communists" ,
 "Subversives" ,
 "Socialists" ,
 "Writers" ,
 "Unions"},

{"Elected Official", "Middle-Upper	Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Fast Talk" ,
 "Persuade" ,
 "Psychology","APP=1" ,
 "?setval:Choose Office,_office,Small Town Mayor,Senior U.S. Senator,City Government,City Mayor,State Government,Governor,U.S. Representative,U.S. Senator" ,
 "?if:_office= Small Town Mayor",
 "?opt:Skill=`Credit Rating`" ,
 "Skill Bonus=5" ,
 "?else" ,
 "?if:_office= City Government",
 "?opt:Skill=`Credit Rating`" ,
 "Skill Bonus=10" ,
 "?elseif:_office= City Mayor",
 "?opt:Skill=`Credit Rating`" ,
 "Skill Bonus=15" ,
 "?elseif:_office= State Government",
 "?opt:Skill=`Credit Rating`" ,
 "Skill Bonus=20" ,
 "?elseif:_office= Governor",
 "?opt:Skill=`Credit Rating`" ,
 "Skill Bonus=30" ,
 "?elseif:_office= U.S. Representative",
 "?opt:Skill=`Credit Rating`" ,
 "Skill Bonus=40" ,
 "?elseif:_office= U.S. Senator",
 "?opt:Skill=`Credit Rating`" ,
 "Skill Bonus=45" ,
 "?elseif:_office= Senior U.S. Senator",
 "?opt:Skill=`Credit Rating`" ,
 "Skill Bonus=50" ,
 "?endif Local Government" ,
 "Federal Government" ,
 "News Industry" ,
 "Business World" ,
 "Foreign Government" ,
 "Organized Crime"},

{"Field Researcher", "Middle-Upper Middle",
"Accounting" ,
 "Bargain" ,
 "Climb" ,
 "Credit Rating" ,
 "First Aid" ,
 "Jump" ,
 "Library Use" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade" ,
 "Choose 3 Fields of Study,3-3,Anthropology,Archaeology,Astronomy,Biology,Chemistry,Computer Use,Electronics,Forensic Surgery,Generic Skill,Generic Skill 2,Generic Skill 3,Geology,Pharmacy,Physics,Psychology,Sports Medicine,Medicine	","Skills:Credit Rating+20	EDU=2" ,
 "CON=1	News Industry" ,
 "Scholars" ,
 "Grant Foundations" ,
 "Foreign Government" ,
 "Business World" ,
 "Monied Patrons"},

{"Professor/Teacher", "Lower Middle-Upper Middle",
	"Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Library Use" ,
 "Persuade" ,
 "Choose 3 Fields of Study,3-3,Anthropology,Archaeology,Astronomy,Biology,Chemistry,Computer Use,Electronics,Forensic Surgery,Generic Skill,Generic Skill 2,Generic Skill 3,Geology,Pharmacy,Physics,Psychology,Sports Medicine,Medicine	","Skills:Credit Rating+10"	,"EDU=2	Scholars" ,
 "Libraries" ,
 "Universities" ,
 "Local Labs"},

{"Researcher", "Lower Middle-Upper Middle",
	"Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Library Use" ,
 "Choose 3 Fields of Study,3-3,Anthropology,Archaeology,Astronomy,Biology,Chemistry,Computer Use,Electronics,Forensic Surgery,Generic Skill,Generic Skill 2,Generic Skill 3,Geology,Pharmacy,Physics,Psychology,Sports Medicine,Medicine", "EDU=3	Scholars" ,
 "Local Labs" ,
 "Libraries" ,
 "Universities"},

{"Student/Intern", "Pauper-Upper Lower",
"?opt:Native=1" ,
 "Choose:Own Language,1,*Language" ,

 "Library Use" ,
 "Choose 3 Fields of Study,3-3,Anthropology,Archaeology,Astronomy,Biology,Chemistry,Computer Use,Electronics,Forensic Surgery,Generic Skill,Generic Skill 2,Generic Skill 3,Geology,Pharmacy,Physics,Psychology,Sports Medicine,Medicine", "EDU=1	Scholars" ,
 "Libraries" ,
 "Universities" ,
 "Local Labs"},

{"Antique Dealer",	1920	,"Lower Middle-Upper Middle",
"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 "Drive Auto" ,
 "Fast Talk" ,
 "History" ,
 "Library Use" ,
 "Navigate" ,
 "Persuade" ,
 "Antiques", "EDU=1" ,
 "?opt:Skill=`Antiques`" ,
 "Skill Bonus=rand(20)+40	Local Historians" ,
 "Antique Dealers"},

{"Book Dealer", "Upper Lower-Middle",
	"Accounting" ,
 "Bookbinding" ,
 "Printing History" ,
 "Bargain" ,
 "Credit Rating" ,
 "Drive Auto" ,
 
 "Choose:Own Language,1,*Language" ,

 "History" ,
 "Library Use" ,
 "Navigate" ,
 "Choose:Other Language,1,*Language" ,
 "Persuade", "EDU=1" ,
 "?opt:Skill=`Bookbinding`" ,
 "Skill Bonus=rand(20)+40" ,
 "?opt:Skill=`Printing History`" ,
 "?allowdup" ,
 "Skill Bonus=rand(20)+40	Libraries" ,
 "Bibliographers" ,
 "Book Dealers" ,
 "Universities" ,
 "Previous Clients"},

{"Dilettante of Independent Means", "Upper Lower-Wealthy	Credit Rating" ,
 "Choose up to 4 Areas of Interesa , 1-4,Accountina , Air Navigatioa , Anthropologa , Antiquea , Archaeologa , Archera , Architectural Histora , Ara , Art Histora , Artillera , Astronoma , Axa , Bargaia , Bayonea , Biologa , Blackjaca , Bloca , Bookbindina , Chemistra , Clima , Clua , Computer Usa , Conceaa , Crafa , Cthulhu Mythoa , Dark Rooa , Disguisa , Divina , Dodga , Drawina , Drive Auta , Drive Horsea , Electrical Repaia , Electronica , Engravina , Aca , Comeda , Cooa , Danca , Jugglina , Paina , Play Instrumena , Sina , Ventriloquisa , Fast Tala , Fire Fightina , First Aia , Fist/Punca , Flamethrowea , Forensic Surgera , Garrota , Generic Combat Skila , Generic Skila , Geologa , Grappla , Handgua , Head Buta , Heavy Weapona , Hida , Histora , Juma , Kica , Knifa , Laa , Library Usa , Listea , Literature Histora , Locksmita , Machine Gua , Martial Arta , Mechanical Repaia , Medicina , Natural Histora , Navigata , Occula , Operate Heavy Machina , Other Languaga , Own Languaga , Persuada , Pharmaca , Photographa , Physica , Pick Pockea , Pilot Aircrafa , Pilot Airlinea , Pilot Ballooa , Pilot Boaa , Pilot Civil Jea , Pilot Civil Proa , Pilot Dirigibla , Pilot Helicoptea , Pilot Jet Fightea , Printing Histora , Psychoanalysia , Psychologa , Rida , Rifla , Ropa , Shorthana , Shotgua , Sneaa , Sports Medicina , Spot Hiddea , Straight Razoa , Submachine Gua , Swia , Swora , Throa , Traca , Typina , Whip", "Masons or other Fraternal Groups" ,
 "Artists" ,
 "Poets" ,
 "High Society"},

{"Fireman", "Lower Middle-Upper Middle",
	"Axe" ,
 "Climb" ,
 "Dodge" ,
 "First Aid" ,
 "Fire Fighting" ,
 "Jump" ,
 "Rope", "STR=1" ,
 "CON=1" ,
 "?opt:Skill=`Fire Fighting`" ,
 "Skill Bonus=rand(20)+40	Civic Amenities"},

{"Flapper",	1920	,"Upper Lower-Lower Middle",
"Bargain" ,
 "Fast Talk" ,
 "Persuade" ,
 "Psychology", "APP=2"},

{"Gardener/Grave Digger", "Upper Lower-Lower	Bargain" ,
 "Choose up to 3 Areas of Interesa , 1-3,Accountina , Air Navigatioa , Anthropologa , Antiquea , Archaeologa , Archera , Architectural Histora , Ara , Art Histora , Artillera , Astronoma , Axa , Bargaia , Bayonea , Biologa , Blackjaca , Bloca , Bookbindina , Chemistra , Clima , Clua , Computer Usa , Conceaa , Crafa , Cthulhu Mythoa , Dark Rooa , Disguisa , Divina , Dodga , Drawina , Drive Auta , Drive Horsea , Electrical Repaia , Electronica , Engravina , Aca , Comeda , Cooa , Danca , Jugglina , Paina , Play Instrumena , Sina , Ventriloquisa , Fast Tala , Fire Fightina , First Aia , Fist/Punca , Flamethrowea , Forensic Surgera , Garrota , Generic Combat Skila , Generic Skila , Geologa , Grappla , Handgua , Head Buta , Heavy Weapona , Hida , Histora , Juma , Kica , Knifa , Laa , Library Usa , Listea , Literature Histora , Locksmita , Machine Gua , Martial Arta , Mechanical Repaia , Medicina , Natural Histora , Navigata , Occula , Operate Heavy Machina , Other Languaga , Own Languaga , Persuada , Pharmaca , Photographa , Physica , Pick Pockea , Pilot Aircrafa , Pilot Airlinea , Pilot Ballooa , Pilot Boaa , Pilot Civil Jea , Pilot Civil Proa , Pilot Dirigibla , Pilot Helicoptea , Pilot Jet Fightea , Printing Histora , Psychoanalysia , Psychologa , Rida , Rifla , Ropa , Shorthana , Shotgua , Sneaa , Sports Medicina , Spot Hiddea , Straight Razoa , Submachine Gua , Swia , Swora , Throa , Traca , Typina , Whip", "STR=1" ,
 "CON=1", "Immune to sanity losses from visiting graveyards at night, unearthing graves, etc."},

{"Hobo", "Pauper	Bargain" ,
 "Climb" ,
 "Fast Talk" ,
 "Hide" ,
 "Jump" ,
 "Listen" ,
 "Natural History" ,
 "Sneak" ,
 "Spot Hidden" ,
 "Persuade	", "Hobos" ,
 "Railroad Guards" ,
 "Local Residents	Hobos have a special written language ofsigns and symbols. These unobtrusive messages, scratched on walls and rocks, warn of vicious dogs and sadistic railroad guards, or inform as to where to get a good meal or find a place to sleep."},

{"Librarian", "Lower Middle-Middle",
	"Accounting" ,
 
 "Choose:Own Language,1,*Language" ,

 "Library Use" ,
 "Choose:Other Language,1,*Language" ,
 "Choose 3 Favorite Reading Topica ,  1-3,Accountina ,  Air Navigatioa ,  Anthropologa ,  Antiquea ,  Archaeologa ,  Archera ,  Architectural Histora ,  Ara ,  Art Histora ,  Artillera ,  Astronoma ,  Axa ,  Bargaia ,  Bayonea ,  Biologa ,  Blackjaca ,  Bloca ,  Bookbindina ,  Chemistra ,  Clima ,  Clua ,  Computer Usa ,  Conceaa ,  Crafa ,  Cthulhu Mythoa ,  Dark Rooa ,  Disguisa ,  Divina ,  Dodga ,  Drawina ,  Drive Auta ,  Drive Horsea ,  Electrical Repaia ,  Electronica ,  Engravina ,  Aca ,  Comeda ,  Cooa ,  Danca ,  Jugglina ,  Paina ,  Play Instrumena ,  Sina ,  Ventriloquisa ,  Fast Tala ,  Fire Fightina ,  First Aia ,  Fist/Punca ,  Flamethrowea ,  Forensic Surgera ,  Garrota ,  Generic Combat Skila ,  Generic Skila ,  Geologa ,  Grappla ,  Handgua ,  Head Buta ,  Heavy Weapona ,  Hida ,  Histora ,  Juma ,  Kica ,  Knifa ,  Laa ,  Library Usa ,  Listea ,  Literature Histora ,  Locksmita ,  Machine Gua ,  Martial Arta ,  Mechanical Repaia ,  Medicina ,  Natural Histora ,  Navigata ,  Occula ,  Operate Heavy Machina ,  Other Languaga ,  Own Languaga ,  Persuada ,  Pharmaca ,  Photographa ,  Physica ,  Pick Pockea ,  Pilot Aircrafa ,  Pilot Airlinea ,  Pilot Ballooa ,  Pilot Boaa ,  Pilot Civil Jea ,  Pilot Civil Proa ,  Pilot Dirigibla ,  Pilot Helicoptea ,  Pilot Jet Fightea ,  Printing Histora ,  Psychoanalysia ,  Psychologa ,  Rida ,  Rifla ,  Ropa ,  Shorthana ,  Shotgua ,  Sneaa ,  Sports Medicina ,  Spot Hiddea ,  Straight Razoa ,  Submachine Gua ,  Swia ,  Swora ,  Throa ,  Traca ,  Typina ,  Whip"},

{"Merchant Marine", "Upper Lower",
"Anthropology" ,
 "Climb" ,
 "Electrical Repair" ,
 "Jump" ,
 "Mechanical Repair" ,
 "Operate Heavy Machine" ,
 "Other Language", "STR=1" ,
 "CON=1" ,
 "EDU=-2	Seaman`s Union" ,
 "Smugglers"},

{"Museum Curator", "Upper Lower-Upper Middle", 
"",
	"Accounting" ,
 "Bargain" ,
 "Credit Rating" ,
 
 "Choose:Own Language,1,*Language" ,

 "Library Use" ,
 "Persuade	", "Scholars" ,
 "Publishers" ,
 "Museum Patrons" ,
 "Universities"},

{"Occultist", "Pauper-Lower	Anthropology" ,
 
 "Choose:Own Language,1,*Language" ,

 "History" ,
 "Library Use" ,
 "Occult" ,
 "Other Language	", "Libraries" ,
 "Occult Societies" ,
 "Occultists"},

{"Parapsychologist, Scientific", "Upper Lower-Lower Middle",
"Anthropology" ,
 "Hypnotism" ,
 "Electrical Repair" ,
 "Library Use" ,
 "Mechanical Repair" ,
 "Occult" ,
 "Photography	", "Universities" ,
 "Parapsychological Publications"},

{"Surveyor", "Upper Lower-Middle",
	"Accounting" ,
 "Bargain" ,
 "Library Use" ,
 "Natural History" ,
 "Navigate" ,
 "Photography" ,
 "Spot Hidden	", "Records Offices"},

{"Undertaker", "Lower Middle-Upper Middle",
	"Accounting" ,
 "Bargain" ,
 "Biology" ,
 "Credit Rating" ,
 "Persuade" ,
 "Psychology", "Considering the nature of the undertaker`s work, certain sanity losses regarding corpses, blood, or accident victims might be safely reduced or ignored."},

{"Zookeeper", "Lower Middle-Middle",
	"Accounting" ,
 "Biology" ,
 "First Aid" ,
 "Natural History" ,
 "Medicine[Medicine (veterinary)]" ,
 "Pharmacy	", "University Zoology Department"}
 
}
