cthulhuskills={
{"Accounting", "10", "Grants understanding of accountancy procedures, and reveals the financial functioning of a business or person. Inspecting the books, one might detect cheated employees, siphoned-off funds, payment of bribes or blackmail, and whether or not the financial condition is better or worse than claimed. Looking through old accounts, one could see how money was gained or lost in the past", "grain, slave-trading, whiskey-running, etc.) and to whom and for what payment was made."},    
    
{"Anthropology", "01", "Enables the user to identify and understand an individual’s way of life from his behavior. If the skill-user observes another culture from within for a time, or works from accurate records concerning an extinct culture, he or she may make simple predictions about that culture’s ways and morals, even though the evidence may be incomplete. Studying the culture for a month or more, the anthropologist begins to understand how the culture functions and, in combination with Psychology, may predict the actions and beliefs of representatives. Essentially useful only with existing human cultures."},    
    
{"Archaeology", "01", "Allows dating and identification of artifacts from past cultures and the detecting of fakes. Having thoroughly inspected a site, the user might deduce the purposes and way of life of those who left the remains. Anthropology might aid in this. Archaeology also help identify written forms of extinct human languages."},    
    
{"Art", "05", "Specify song, some musical instrument, painting, cooking, etc.—any non-literary art which a creative person might seriously pursue through life. With a success, the performance or creation is pleasing and the audience is satisfied. Failure indicates that the artist was off-key or inexpressive. Lovecraft’s artists invoke the traditional muses, but the keeper might allow wider definitions of “art”. The points where Art ends and Craft begins vary with each keeper. The investigator sheet contains blank spaces for different versions of this skill. The player should note the style or medium: opera singer, oil painter, etc."},    
    
{"Astronomy", "01", "The user knows or knows how to find out which stars and planets are overhead at a particular day or hour of day or night, when eclipses and meteor showers occur, and the names of important stars, and something of current perceptions about life on other worlds, the existence or the formation of galaxies, and so on. An academic might be able to calculate orbits, discuss stellar life cycles, and", "in the present) have a specialty such as infrared astronomy or long-baseline interferometry."},    
    
{"Bargain", "05", "The skill of obtaining something for an agreeable price. The bargainer must state the price at which he or she wishes to purchase the item and, for each 2% difference between that price and the asking price, he or she must subtract 1 percentile from his Bargain skill. The seller will not take a loss, no matter how good the bargaining. The keeper usually determines the bottom- line amount secretly. Example: Harvey Walters purchases a shotgun in Germany, to take with him while he investigates the disappearance of his manservant, Kurt, in the old ruins nearby.", "Kurt failed a Sneak roll and was caught by the Inhabitant.) The elderly shopkeeper asks $100 American for the weapon, and Harvey is on a limited budget. Harvey offers the shopkeeper $70, and his player makes a D100 roll. Harvey has Bargain 20%, but he wants the gun for 30% less than normal, so his chance for success is reduced by 15 percentiles to only 05%. The player rolls 22—a failure. Harvey then offers $80, increasing his chances to 10%. The player rolls 02, a success. By implication, use this skill in any negotiation which features an exchange of value. Combination rolls with Credit Rating, Fast Talk, or Persuade might help in bargaining. A simple bargain may be struck in a few minutes. A complex contract might take weeks, and Bargain might then work in combination with Law."},    
    
{"Biology", "01", "The science of life, including botany, cytology, ecology, genetics, histology, microbiology, physiology, zoology, and so on. The investigator’s understanding reflects the era of play. With this skill one might develop a vaccine against some hideous Mythos bacterium, or isolate the hallucinogenic properties of some jungle plant."},    
    
{"Chemistry", "01", "A study of the composition of substances, the effects of temperature, energy, and pressure upon them, and how they affect one another. With chemistry, one might create or extract complex chemical compounds, including simple explosives, poisons, gases, and acids, requiring at least a day or so with the proper equipment and chemicals. The user could also analyze an unknown substance, given proper equipment and reagents."},    
    
{"Climb", "40", "A Climb roll must be attempted every 10 to 30 vertical feet, depending on the difficulty of the climb as the keeper perceives it. Conditions such as firmness of surface, wind, visibility, rain, etc., may be factors. If an investigator needs to climb quietly, match the player’s D100 roll against both Climb and Sneak. If succeeding in Climb but failing in Sneak, he or she climbed successfully, but made noise. If the Climb failed but the Sneak succeeded, he or she fell, but did not attract attention."},    
    
{"Computer Use", "01", "This skill is not needed to use microcomputers nor to run ordinary commercial software. Special manipulations of a microcomputer system may require this roll. A skill for the present day, Computer Use allows the investigator to program in various computer languages to achieve his or her end: perhaps write new programs, retrieve and analyze obscure data, break into a secured system, explore a complicated network, or detect or exploit intrusions, back doors, and viruses. Each application of the skill takes half a day or more, and perhaps more than one successful roll. The keeper must judge the actual requirements and results, and should probably make secret Computer Use rolls at times. Once inside a network, Library Use might be employed also."},    
    
{"Conceal", "15", "Allows the visual covering up, secreting, or masking of an object or objects, perhaps with debris, cloth, or other intervening or illusionpromoting materials, perhaps by making a secret panel or false compartment, or perhaps by repainting or otherwise changing an item’s characteristics to escape detection. With it, a person might be secreted from sight, but could not be disguised to evade even a cursory inspection. Larger objects of any sort should be increasingly hard to conceal. Things larger than elephants should not be concealed by one person, though they might be by a group. Compare with the Hide skill."},    
    
{"Craft", "05", "A craft is a specialized skill for making and repairing practical things or for creating pleasing effects. It requires manual dexterity or artful application. As an occupation, a craft typically provides more income than laboring, but not as much as a profession. A multitude of crafts exist, from house painter to liontamer to safecracker. Particularize a craft on the investigator sheet, in the same general fashion as for Art: for instance, Craft", "Cobbler), Craft", "Barber), or Craft", "Blow Vacuum Tube). Making or repairing something typically requires equipment and time, to be determined by the keeper if necessary. With a very low result, a craftsman might make an exceptionally fine item. With a failing roll, the item might break on its first use, or fail to fit into some larger whole. A successful Craft roll might provide information about an item, such as where or when it might have been made, reveal some point of history or technique concerning it, or who might have made it."},    
    
{"Credit Rating", "15", "Narrowly, how prosperous and confident the investigator seems to be. This is the investigator’s chance to panhandle or get a loan from a bank or business, and it is also the chance for the investigator to pass a bad check or to bluff past a demand for credentials. In small towns, or in narrow societies such as Edwardian England, everyone knows everyone, and Credit Rating amounts to an index of personal reputation as well as monetary worth. Thus Credit Rating might ebb and flow because of scandal or personal behavior, while the loss or accumulation of money effected minor change or no change. As appropriate, the keeper may cause a character to make clear such distinctions."},    
    
{"Cthulhu Mythos", "00", "This skill differs from the others in the game. No starting investigator may take points in Cthulhu Mythos either with occupation points or with personal interest points. There is no check box for Cthulhu Mythos on the investigator sheet, because successful use of the skill does not offer an increase in the investigator’s percentiles in the skill. Instead, points in Cthulhu Mythos are gained by encounters with the Mythos which result in insanity, by optional insane insights into the true nature of the universe, and by reading forbidden books and other Mythos writings. On occasion, witnessing some ceremony or participating in some event might prompt a keeper to award Cthulhu Mythos points as well, but that is up to the keeper. A few Mythos points may be useful, but investigators do not want many of them, because 99 minus an investigator’s Cthulhu Mythos points represents the maximum Sanity points possible to an investigator. As Mythos points proliferate, they crowd out Sanity points, and leave the investigator vulnerable. See Sanity, p. 75ff., for more about this. The Cthulhu Mythos skill does have useful applications. Whenever spoor or other evidence of Mythos monsters is found, a successful D100 roll against this skill allows the investigator to identify the entity, deduce something about its behavior, or guess at some property it may possess. A successful Mythos roll also might allow an investigator to remember some fact concerning the Mythos, identify a spell by seeing it cast, remember that a particular spell or kind of information may be in a particular Mythos tome, or achieve some other task. No human, even one with 99% Cthulhu Mythos, ever approaches complete knowledge of the Mythos. It is fair to say that not even Great Old Ones do. Their 100% scores represent convenient comparisons against what humans can achieve, not a thorough plumbing of the mysteries of the Mythos. Perhaps the Outer Gods know it all, if they bother to think about such things. But only gods can cope with infinity. The cruel darkness of the Mythos extends forever. Seeming mastery of its puzzles is temporary, local, and illusory."},    
    
{"Disguise", "01", "The user changes posture, costume, and/or voice in order to seem another person or another sort of person. Theatrical makeup may help. Dim lighting definitely helps. Increase the chance for detection if the disguise involves significant differences in sex, age, size, or language. To look like a specific person, as opposed to a particular kind of person, halve the Disguise skill percentage—this sort of illusion is best maintained by distance. A successful Spot Hidden or a Psychology roll might lead an observer to suspect someone in disguise. A successful Fast Talk roll by the player of the disguised character lowers the success chance for either of those skills by 10 percentiles. Though explaining die results is the province of the keeper, a low and successful D100 result might give the disguised character some ability to issue convincing orders or to pass inspection by intimates. A failed Disguise roll causes onlookers to notice uncharacteristic behavior or expression. A very high failure, from 90 to 00, declares in effect, “This person is suspicious! Investigate immediately!”"},    
    
{"Dodge", "DEX x2", "Allows an investigator instinctively to evade blows, thrown missiles, attacks from ambush, and so forth. A character attempting Dodge in a combat round may also parry, but not attack. Dodge can increase through experience, like other skills. If an attack can be seen, a character can try to dodge it. Against guns, a defender can try to dodge only the first bullet fired at him in a round."},    
    
{"Drive Automobile / Horses", "20", "Anyone with this skill can drive a car or light truck, make ordinary maneuvers, and cope with ordinary vehicle problems. If the investigator wants to lose a pursuer or trail someone, both participants might attempt Driving rolls until one fails and the other succeeds. For more complicated chases, consult the optional auto chase rules, p. 284. Dangerous maneuvers always call for Drive rolls. In the 1890s, this skill is Drive Horses, with equivalent benefits and dangers. This represents a one-horse buggy or cart, or a two- or four-horse wagon or coach. Those of that era who wish Drive Automobile start at 01%. Investigators of later eras similarly would begin Drive Horses at 01%."},    
    
{"Electrical Repair", "10", "Enables the investigator to repair or reconfigure electrical equipment such as auto ignitions, electric motors, fuse boxes, and burglar alarms. In the present-day, has little to do with Electronics. To fix an electrical device may require special parts or tools. Jobs in the 1920s may call for this skill and for Mechanical Repair in combination."},    
    
{"Electronics", "01", "For trouble-shooting and repairing electronic equipment. Allows simple new electronic devices to be made. This is a skill for the present day—use Physics and Electrical Repair for electronic developments in the 1890s and 1920s. Unlike the Electrical Repair skill, parts needed for Electronics work cannot be jury-rigged: they are designed for precise jobs. Without the right microchip or circuit board, the skill user is out of luck."},    
    
{"Fast Talk", "05", "Causes the target to agree with the user for a short time. Without reflecting, the target signs the paper, allows the trespass, lends the automobile, or whatever else within reason is asked. Given a little more time to think and the benefit of a successful Idea roll, the target comes to his or her senses, and the Fast Talk loses effect. Example: Count von Samme succeeds with a Fast Talk pitch, and Harvey goes upstairs to find a fountain pen with which to sign the Count’s fraudulent contract. As he rummages around, Harvey is absent from the Count long enough to begin to think for himself. The keeper asks for an Idea roll. It succeeds. Harvey comes to his senses and returns determined not to sign. The Count must renew his pitch some other time, or change tactics and attempt to Persuade Harvey. In a few game minutes, Fast Talk may pass off suspect goods as valuable, false facts as reliable, and fine items as not worth bothering about. In contrast, Persuade and Bargain may take hours or days to conclude. Fast Talk is quick to take effect, but it can be used at most on a handful of people. Fast Talk will not work on targets whose minds are made up; use Persuade instead."},    
    
{"First Aid", "30", "The percentage chance of awakening an unconscious or stunned comrade, setting a broken limb, treating burn damage, resuscitating a drowning victim, etc. First Aid has no effect on diseases or subtle physical ailments, nor on poisonings unless the keeper allows the roll. Treated with First Aid, an investigator’s healing rate stays at 1D3 points per week.", "Moved to a hospital and successfully treated with Medicine, that rate rises to 2D3 per week.) Failure in applying First Aid requires that the user wait some reasonable amount of time to try again", "something new, presumably, since what was done didn’t work), but another practicioner could make an attempt in the next round.   A success with this skill allows the user immediately to heal 1D3 hit points of a single attack or injury. Thus an investigator suffering multiple gunshot wounds might receive First Aid for each, as long as they were not incurred in the same combat round.   In the same or the succeeding combat round, an investigator who has just died may be returned to life if the emergency treatment raises hit points to at least +1.   A success with First Aid immediately awakens any victim of a knock-out attack and, if the keeper wishes, anyone unconscious for other reasons. Once a character has had First Aid successfully applied to an injury, further applications either of First Aid or of Medicine have no effect on that injury. A new injury would be treated independently. An application of the skill takes a combat round, or as the keeper determines. See also Medicine."},    
    
{"Fist/Punch", "50", "A self-explanatory skill, which might be depicted as a closed fist, a karate chop, a roundhouse punch, a violent slap, etc. One can use Fist/Punch to parry Kick and Head Butt, Martial Arts can add to the skill’s impact, and the knock-out rule applies to it."},    
    
{"Geology", "01", "Enables an investigator to tell the approximate age of rock strata, recognize fossil types, distinguish minerals and crystals, locate promising sites for drilling or mining, evaluate soils, and anticipate volcanism, seismic events, avalanches, and other such phenomena. Sherlock Holmes was expert in London-area soils, and could trace a man’s movements by studying the dirt on his boots."},    
    
{"Grapple", "25", "A Grapple is a special personal attack, frequently chosen to subdue an opponent without harming him. This attack may be parried by a countering successful Grapple or other attack by the target, but only in the first round of attack. If a Grapple attack succeeds in the first round and is not neutralized, then the attacker holds the target and may thereafter exercise one of several options.   Immobilize the target by overcoming the target’s STR with his or her own STR, using the Resistance Table. With a success, the target is held fast indefinitely, until the grappler attempts another action.   Knock down the target. If used, this option automatically succeeds.   Knock out the target in the first or a later round: see the knock-out rule, p. 60.   Disarm the target. With successful Grapples in consecutive rounds, an investigator could Grapple to prevent a hand-tohand attack in the first round and then seize the weapon or weapon hand in the second round.   Physically injure the target. The opponent already must be successfully grappled. Then the grappler must receive a second successful Grapple roll in that round, or a successful Grapple in some later round. Success costs the target 1D6 hit points plus the attacker’s damage bonus. Harm in subsequent rounds requires a new Grapple success in those rounds, and the amount of injury done remains the same.   Strangle the target. Beginning in the round in which the intention is stated, the target begins to asphyxiate as per the Drowning rules. This continues in subsequent rounds. The attacker needs no further Grapple rolls. In either injury-making Grapple, the victim can escape only by a successful STR match on the Resistance Table. Combine STRs if two people are attacking."},    
    
{"Handgun", "20", "Use for all pistol-like firearms when firing discrete shots. For machine pistols", "MAC-11, Uzi, etc.), in the present day, use the Submachine Gun skill when firing bursts. The rate-of-fire difference between handguns is partly from recoil and time needed to take new aim on the target, and partly from the difference in mechanism between a revolver and a semi-automatic. Properly loading and firing a black-powder handgun may, at the keeper’s option, require a successful History roll as well."},    
    
{"Head Butt", "10", "The essential barroom brawl skill, Head Butt is applied to the belly of an opponent, or else to his temple, crown, nose, chin, or back of the head. This personal attack can be made in cramped surroundings. It is surprisingly quick and of demoralizing intensity. One cannot parry with Head Butt, but Martial Arts can add to its effect. The knock-out rule can be applied to it."},    
    
{"Hide", "10", "As opposed to Conceal, Hide concerns the individual user’s ability to escape detection in an unprepared position. Use this skill only in a pursuit situation, or when under surveillance or patrol. It lets the user choose objects, bushes, deep shadows, etc., in which to lurk for a while. Some sort of cover must be present. In an area being watched, the user can move while hiding. Figure the chance for successful movement by halving the Hide skill amount."},    
    
{"History", "20", "Enables an investigator to remember the significance of a country, city, region, or person, as pertinent. Lessen the chance if the facts are obscure. A successful History roll might be used to help identify tools, techniques, or ideas familiar to ancestors, but little known today."},    
    
{"Jump", "25", "With a success, the investigator can leap up vertically and grab to his or her own height, safely leap down vertically to his or her own height, jump horizontally from a standing start across a gap for a distance equal to the jumper’s own height, or run and then jump horizontally to a distance of twice the jumper’s own height. If falling from a height, a successful Jump prepares for the fall, subtracting 1D6 hit points from those lost to the injury."},    
    
{"Kick", "25", "Whether a straight forward kick to the groin or the jaw, an elegant karate-style flying kick, or a kick with both legs while lying on a floor, a Kick is powerful enough to do damage wherever it lands. A Kick may parry and Martial Arts may add to its effectiveness, but do not apply the knock-out rule to Kick except in rare circumstances."},    
    
{"Law", "05", "Represents the chance of knowing pertinent law, precedent, legal maneuver, or court procedure. The practice of law as a profession can lead to great rewards and political office, but it requires intense application over many years. A high Credit Rating is crucial to it. No other profession is so easily sullied by the bizarre behavior common to investigators. In the United States, one’s practice of law must be sanctioned by the State Bar of a particular commonwealth or state. In another country, halve the chance for success with this skill, unless the character has spent 30-INT months studying that nation’s law."},    
    
{"Library Use", "25", "In many ways this is the most important skill in the game. Library Use enables an investigator to find a given book, newspaper, or reference in a library or collection of documents, assuming that the item is there. Each use of this skill marks four hours of continuous search. An investigator rarely gets more than two tries per day. This skill can locate a locked case or rare-book special collection, but Fast Talk, Persuade, Bargain, Credit Rating, a bribe, or special credentials might be needed to get at the books."},    
    
{"Listen", "25", "Measures the ability of an investigator to interpret and understand sound, including overheard conversations, mutters behind a closed door, and whispered words in a cafe. The keeper may use it to determine the course of an impending encounter: was your investigator awakened by that crackling twig? By extension, a high Listen can indicate general awareness in a character."},    
    
{"Locksmith", "01", "The user may repair locks, make keys, or open locks with the aid of skeleton keys, picks, and other tools. Especially difficult locks may lower the chance for success. A locksmith can open car doors, hot-wire autos, jimmy library windows, figure out Chinese puzzle boxes, and penetrate ordinary commercial alarm systems. Sophisticated safes, vaults, and other serious defensive systems are beyond this skill. Keepers might combine Locksmith with DEX or POW rolls to cover a variety of surreptitious situations."},    
    
{"Machine Gun", "15", "Use this skill whenever firing bursts from a bipod or tripod mounted weapon. If single shots are fired from a bipod, use the Rifle skill if it is higher. The differences between assault rifle, submachine gun, and light machine gun are tenuous today."},    
    
{"Martial Arts", "01", "Use in combination with an attack with Fist/Punch, Head Butt, Kick, or Grapple. If the attack roll is equal to or less than the attacker’s Martial Arts percentage, the attack does double damage: thus Fist/Punch would do 2D3 plus normal damage bonus. Martial Arts doubles the damage done if the attack strikes home, but do not double any damage bonus.   A person with Martial Arts may choose which attack to parry just before that attack, and does not need to make a parry statement at the beginning of the round.   Even with Martial Arts, bullets and other projectiles cannot be parried. People develop martial arts to compensate for forcible disarmament: judo, aikijutsu, aikido, capoera, karate, savat, tae kyun or tae kwon do, white crane kung fu, 7 straws praying mantis kung fu, etc. Choose one or invent a new one. In earlier days, these schools were secret and their techniques jealously guarded. Outside their cultures, martial arts are little known until the present era."},    
    
{"Mechanical Repair", "20", "This allows the investigator to repair a broken machine, or to create a new one. Basic carpentry and plumbing projects can be performed. Special tools or parts may be required. This skill can open common household locks, but nothing more advanced. See the Locksmith skill. Mechanical Repair is a companion skill to Electrical Repair, and both may be necessary to fix complex devices such as an auto or an aircraft."},    
    
{"Medicine", "05", "The user diagnoses and treats accidents, injuries, diseases, poisonings, etc., and makes public health recommendations. If an era has no good treatment for a malady, the effort is limited, uncertain, or inconclusive. Failure in application requires that the user wait some amount of time to try again, but another practicioner could make his or her attempt in the next round.   In an emergency, the successful user of Medicine can immediately restore 1D3 hit points, once per wound or injury.   In the same or the succeeding combat round, an investigator who has just died may be returned to life if hit points rise to at least +1.   An investigator successfully treated with Medicine heals at 2D3 hit points per game week, including the first week.   Including any emergency treatment, the total recovery for the first week of Medicine’s application could be 3D3 hit points.   A success with Medicine immediately awakens any victim of a knock-out attack and anyone unconscious for other reasons.   The keeper may rule that a medical condition is not treatable. See also First Aid."},    
    
{"Natural History", "10", "Originally the study of plant and animal life in its environment. By the nineteenth century this study had long separated into many academic disciplines. As a game skill it represents the traditional knowledge and personal observation of farmers, fishermen, inspired amateurs, and hobbyists. It identifies species, habits, and habitats in a general way and is able to guess at what may be important to a particular species. Natural History information may or may not be accurate—this is the region of appreciation, judgment, tradition, and enthusiasm. Use Natural History to judge horseflesh at a county fair, or to decide whether a butterfly collection is excellent or just excellently framed."},    
    
{"Navigate", "10", "Allows the user to find his or her way in storms or clear weather, in day or at night. Those of higher skill are familiar with the astronomical tables, charts, instruments, and satellite location gear as they exist in the era of play. Roll results for such a skill should be kept secret, a matter for the investigators to attempt and then to witness the results. One could also use this skill to measure and map an area, whether an island of many square miles or the interior of a single room."},    
    
{"Occult", "05", "The user recognizes occult paraphernalia, words, and concepts, and identifies grimoires of magic and occult codes when he sees them. The occultist is familiar with the families of secret knowledge passed down from Egypt and Sumer, from the Medieval and Renaissance West, and perhaps from Asia and Africa as well. Comprehending certain books may provide percentiles of Occult. Some occult books are noted in the Magic chapter, p. 92. This skill does not apply to spells, books, and magic of the Cthulhu Mythos, but occult concepts are often adopted by worshipers of the Great Old Ones."},    
    
{"Operate Heavy Machine", "01", "Required to drive and operate a tank, backhoe, steam shovel, or other large-scale construction machine. Once the skill is known, no skill roll is needed except for difficult or dangerous tasks, or bad or dangerous conditions. For very different sorts of machines, the keeper may decide to lower an investigator’s nominal skill if the problems encountered are mostly unfamiliar ones: someone used to running a bulldozer, for instance, will not be quickly competent with the steam turbines in a ship’s engine room."},    
    
{"Other Language", "01", "Specify the language. An individual can know any number of languages. The skill represents the user’s chance to understand, speak, read, and write in a language other than his or her own. Ancient or unknown languages comparable to Aklo should not be chosen, but ordinary earthly languages may be. Occasionally the keeper may determine that a number of separate complex points exist in a document or speech, and call for several such language rolls, one for each point. Similarly, the keeper may momentarily reduce a user’s skill in a language if archaic speech or writing in that language is encountered. A single successful Other Language roll normally comprehends an entire book. If an investigator has several points in a particular Other Language, he or she grasps the gist of normal conversation. A character needs INT x5 or better points in a second language to pass for a native speaker. Blank spaces exist for other languages on the investigator sheet. To identify an unknown present-day human language, use a Know roll. To identify an extinct human language, use an Archeology roll. To identify an alien language, use a Cthulhu Mythos or possibly an Occult roll."},    
    
{"Own Language", "EDU X5", "Specify the language. In infancy and early childhood, most humans use a single language. For most people in the United States, that tongue is some dialect of English. The tongue chosen by the player for the investigator’s Own Language automatically starts at EDU x5: thereafter the investigator understands, speaks, reads, and writes at that percentage or higher. Normally no skill roll is necessary to use Own Language. If a document is extremely difficult to read, or in an archaic dialect, the keeper may reduce the user’s skill chance in that situation. Authors typically have high Own Language skills."},    
    
{"Persuade", "15", "Use Persuade to convince a target about a particular idea, concept, or belief.", "Like Fast Talk, Persuade may be employed without reference to truth.) Unlike Fast Talk, Persuade’s effect lingers indefinitely and insidiously, for years perhaps, until events or another Persuade turn the target’s mind in another direction. The successful application of Persuade might take an hour to several days, depending on what’s being attempted."},    
    
{"Pharmacy", "01", "The user recognizes, compounds, and perhaps dispenses a wide variety of drugs and potions, natural and man-made, and understands side effects and contra-indications. He or she has a good practical knowledge of poisons and antidotes, and can use Pharmacy as a first-aid skill in cases of poisoning. The skill grants no ability to diagnose diseases nor the right to prescribe medicines."},    
    
{"Photography", "10", "Covers both still and motion photography. This skill allows one to take clear pictures, develop them properly, and perhaps enhance half-hidden detail. Failures are blurred or do not show what was desired. In the present day, the skill extends to cover video cameras, video playback equipment, and digital photography."},    
    
{"Physics", "01", "Grants theoretical understanding of pressure, materials, motion, magnetism, electricity, optics, radioactivity, and related phenomena, and some ability to construct experimental devices to test ideas. The degree of knowledge depends on the era of use. Practical devices such as automobiles are not the province of physicists, but experimental devices may be, perhaps in conjunction with Electronics or Mechanical Repair."},    
    
{"Pilot", "01", "The air/water equivalent of Drive Automobile, this is the maneuver skill for flying or floating craft. An investigator might have several versions of this skill in the spaces on the investigator sheet. Each starts at 01%.   Pilot Aircraft skills change by era. Pilot Boat does not change, and does not distinguish between sail and motor craft. Bad weather, bad visibility, and damage apply to air and water craft.   A skill user of less than 15% knows just enough to get into trouble. He or she can sail or fly on a calm day with good visibility, but needs Luck rolls for take-offs and landings, dockings, changing sails, judging wind and current, etc. Keepers must require Pilot rolls for storms, navigation by instrument, low visibility, and other difficult situations. PILOT AIRCRAFT: understands and is increasingly competent with a general class of aircraft named below. Upon any landing, even under the best conditions, a Pilot roll must be made. If conditions are good, double the chance for success. If conditions are bad, the pilot lands at his or her normal chance. A failure may represent damage to the craft, which must be repaired before the next takeoff. Pilot and passengers may walk away or need Luck rolls to avoid serious injury. A result of 00 is a memorable disaster, with at least the death of the pilot.   Each class of aircraft counts as a different skill, and should be listed independently, or as the keeper sees fit: 1890s, Pilot Balloon only; 1920s, Pilot Balloon/ Dirigible/ Civil Prop only; in the present day, Pilot Civil Prop, Pilot Civil Jet, Pilot Airliner, Pilot Jet Fighter, Pilot Helicopter. PILOT BOAT: understands the behavior of small motor and sailing craft in wind, storms, and tides, and can read wave and wind action to suggest hidden obstacles and approaching storms. In a wind, novice sailors will find docking a rowboat difficult."},    
    
{"Psychoanalysis", "01%)Enables the user to staunch temporary and indefinite insanity for a day or so. If the condition persists beyond that period, the unfortunate person relapses, and only time heals the insanity. This emergency treatment takes up to an hour to perform, and can be applied just once per incident of insanity, no matter how many analysts are available.   Treatment by a psychotherapist can add Sanity points during indefinite insanity. See Sanity, p. 79.   Psychoanalysis cannot increase a person’s Sanity points beyond POW x5, nor above 99-Cthulhu Mythos. The skill refers to the range of emotional therapies, not just to Freudian procedures. Formal psychotherapy was little-known in the 1890s, though some procedures are as old as humanity. Sometimes it was looked on as a fraudulent study even in the 1920s. The common term then for an analyst or scholar of emotional disorders was alienist. In the present day, a combination of therapies has evolved, and this skill now could be justly named Psychiatric Treatment."},    
    
{"Psychology", "05", "A skill common to all humans, it allows the user to study an individual and form an idea of his or her motives and character. In general, the keeper should make the rolls for this skill and keep the results secret, announcing only the information, true or false, that the user gained by employing it. Players should not expect that this skill penetrates skillful deceit unless the person’s confidence somehow has been shaken."},    
    
{"Ride", "05", "Intended to apply to saddle horses, donkeys, or mules. A camel might be ridden successfully at a lowered percentage chance. The skill grants knowledge of basic care of the riding animal, riding gear, and how to handle the steed at the gallop or on difficult terrain. Should a steed unexpectedly rear or stumble, the rider’s chance of remaining mounted equals his or her Ride. If an investigator falls from a mount, either because the animal has collapsed, fallen, or died, or because a Ride roll failed, he or she loses 1D6 hit points in the accident. A successful Jump roll saves 1D6 hit points. Wielding a weapon effectively while riding takes both a weapon skill and a Ride skill in excess of 50%. The keeper might apply modifiers to reflect a particular situation."},    
    
{"Rifle", "25", "The user can fire any type of rifle, whether leveraction, bolt-action, or semi-automatic. When a military assault rifle fires a single shot or burst, use this skill. When a shotgun fires a rifled slug, use this skill. Shots per round mostly vary because of the weapon’s action and recoil, and the subsequent time needed to reacquire the target. At the keeper’s option, use of a blackpowder rifle requires a History roll as well to load and fire it properly. At the keeper’s option, combine Rifle and Shotgun as a single skill, differentiating only between pellet and slug ammunition."},    
    
{"Shotgun", "30", "With this skill any scatter-gun can be fired. Since the load expands in a spreading pattern, the user’s chance to hit does not decrease with range, but the damage done does. At ranges from 10-20 yards, 1D3 closetogether targets can be hit with one round, and from 20-50 yards, 1D6 such targets can be hit. The keeper decides whether the targets are close enough for this rule. Double-barreled shotguns can be sawed off, for purposes of concealment and portability. In the United States, such weapons are illegal by the 1920s. If firing a rifled slug, use the Rifle skill. At the keeper’s option, combine Rifle and Shotgun as a single skill, differentiating only between pellet and slug ammo."},    
    
{"Sneak", "10", "The art of moving quietly, without alerting those who might hear. Used in combination with Hide, the investigator makes a single D100 roll, the result of which is matched against the investigator’s percentages in both skills. Use this combination when silent movement is necessary. See also Hide."},    
    
{"Spot Hidden", "25", "This skill allows the user to spot a secret door or compartment, notice a hidden intruder, find an inconspicuous clue, recognize a repainted automobile, become aware of ambushers, notice a bulging pocket, or anything similar. This is an important skill in the game."},    
    
{"Submachine Gun", "15", "When firing any machine pistol or submachine gun, use this skill. Present-day machine pistols, such as the Skorpion, may be so small that the Handgun skill should be used when firing single shots from them. No submachine guns exist in the 1890s."},    
    
{"Swim", "25", "The ability to float and to move through water or other liquid. Only roll Swim in times of crisis or danger when the keeper thinks it appropriate. A failing Swim roll starts the drowning procedure. Someone drowning may receive a Swim roll attempt each round—with a success, he or she reaches the surface and breathes. With a second success, he or she can begin to move through the water. If the second Swim roll fails, drowning begins again."},    
    
{"Throw", "25", "To hit a target with an object, or to hit a target with the right part of the object thrown", "such as the blade of a knife or hatchet), use Throw. A palm-sized object of reasonable balance can be hurled three yards for each STR point exceeding the object’s SIZ. An object designed to be thrown can be hurled up to six yards for each STR point in excess of the object’s SIZ, and perhaps bounce on for more. Keepers must choose the multiplier suitable to the baseball, javelin, etc. If the Throw roll fails, then the object lands at some random distance from the target. Compare the closeness of the die roll result to the highest number which would have indicated success, and choose a distance in yards between target and thrown object that feels comparable."},    
    
{"Track", "10", "With Track, an investigator can follow a person, vehicle, or animal over soft earth and leaves. Subtract 10% from the chance for success for each day that has passed since the tracks were made. Rain may make tracking impossible. A being cannot be tracked across water, over concrete, or at night except in unusual circumstances. "}};
--end coc skills