motivations={"to aid a group/person with their motivation",
"to aid others in finding a way of life/living condition",
"to aid others in gaining a hobby/activity",
"to allow others to engage in a pleasurable activity",
"to avoid a disaster/event (possible/planned/ongoing)",
"to avoid a habit/addiction",
"to avoid a way of life/living condition",
"to avoid affecting some endeavour",
"to avoid an undesired task/job",
"to avoid danger/violence/conflict",
"to avoid fame/attention",
"to avoid influencing a group/person",
"to avoid justice/punishment",
"to avoid learning certain information/knowledge",
"to avoid relationships",
"to avoid the control of a group/person",
"to avoid the source of a phobia/allergy",
"to avoid the vengeance/retribution",
"to break up a group",
"to break up a relationship",
"to bring a group/person to justice",
"to bring vengance/retribution to a group/person",
"to contain chaos/anarchy",
"to contain the spread of a belief",
"to contain the spread of certain information",
"to contain violence/conflict",
"to continue with a hobby/activity",
"to create a place/thing",
"to deny others a task/job",
"to deny others power",
"to deny others wealth",
"to destroy a habit/addiction of others",
"to destroy a place/thing",
"to destroy an alliance",
"to destroy the source of a phobia/allergy",
"to destroy the way of life/living condition of others",
"to diminish ones own reputation",
"to diminish the reputation of a group/person",
"to diminish the reputation of a place/thing",
"to discover a place/thing",
"to eliminate a hazard/scourge",
"to eliminate a task/job of another",
"to eliminate the control of others over a group/person",
"to encourage a relationship",
"to encourage an alliance",
"to engage in a pleasurable activity",
"to enhance the reputation of a group/person",
"to enhance the reputation of a place/thing",
"to ensure that a disaster happens",
"to ensure that an event happens",
"to financialy ruin another group/person",
"to find a way of life/living condition",
"to find danger/excitement",
"to find enlightenment",
"to find the organizer of an event",
"to find the source of a disaster",
"to find the source of a phobia/allergy",
"to forment chaos/confusion/anarchy",
"to gain a hobby/activity",
"to gain a reputation",
"to gain control over a group/person",
"to gain employment",
"to gain fame/attention",
"to gain influence with a group/person",
"to gain knowledge in general",
"to gain possession of a place/thing",
"to gain power",
"to gain responsibility",
"to gain status within a group",
"to gain the friendship of a group/person",
"to gain the love of another",
"to gain wealth",
"to get out of a task/job",
"to get out of an endeavour",
"to guard a place from others",
"to halt a disaster/event",
"to halt the spread of information about a person/group",
"to halt the spread of information about a place/thing",
"to halt the spread of information about an endeavor/event",
"to help other avoid a habit/addiction",
"to help others gain fame/attention",
"to help others get out of a task/job",
"to help others get out of an endeavour",
"to help others keep a low profile",
"to help others keep a task/job",
"to help others keep a way of life/living condition",
"to help others stay alive",
"to help start an endeavour",
"to hinder an endeavour/event",
"to hinder the forces of justice",
"to hinder the vengeance of others",
"to improve a relationship",
"to improve an alliance",
"to improve the influence of a group/person",
"to improve the status of others",
"to improve the wealth of a group/person",
"to join a group",
"to join in an endeavor",
"to keep a certain responsibility",
"to keep a group together",
"to keep a low profile",
"to keep a task/job",
"to keep away from a group/person",
"to keep from gaining power",
"to keep from gaining wealth",
"to keep from getting involved in an endeavour",
"to keep others in an endeavor",
"to keep someone else alive",
"to keep the relationship of a group/person",
"to kill a creature/monster",
"to kill a person",
"to kill members of a group",
"to learn a skill/ability",
"to learn more about a person/group",
"to learn more about an event/endeavour",
"to learn more about an place/thing",
"to leave a group",
"to leave a way of life/living condition",
"to lose a habit/addiction",
"to lose the friendship of a group/person",
"to lose the love of another",
"to lose the possession of a place/thing",
"to maintain a hobby/activity",
"to maintain a reputation",
"to maintain an alliance",
"to maintain power",
"to maintain some other relationship",
"to maintain the condition of a place/thing",
"to maintain the influence of a group/person",
"to maintain the relationships of others",
"to maintain the reputation of a group/person",
"to maintain the strength of an endeavour",
"to maintain wealth",
"to perform a sport/activity",
"to prevent an alliance",
"to prevent conflict/violence",
"to prevent others from finding a way of live/living condition",
"to prevent others from gaining a reputation",
"to prevent others from gaining status",
"to prevent others from getting fame/attention",
"to prevent others from starting a habit/addiction",
"to prevent relationships for another",
"to prevent the control of others by a group/person",
"to prevent the creation of a place/thing",
"to prevent the creation of wealth",
"to prevent the discovery of a place/thing",
"to prevent the influence of another group/person",
"to prevent the possession of a place/thing by others",
"to prevent the relationship of others",
"to prevent the spread of a habit/addiction",
"to prevent the spread of a hobby/activity",
"to prevent the spread of a pleasurable activity",
"to promote a belief",
"to promote an event/endeavor",
"to promote the benefits of a habit/addiction",
"to promote the benefits of a pleasurable activity",
"to promote the benefits of a way of life/living condition",
"to promote the start of a group",
"to protect a belief from unbelievers",
"to protect a thing from others",
"to protect others from the forces of justice",
"to protect others from the forces of vengeance",
"to quell violence/chaos/anarchy",
"to recruit for a task/job/endeavor",
"to reduce ones influence over a group/person",
"to reduce ones responsibilities",
"to reduce ones status in a group",
"to reduce personal wealth",
"to reduce the influence of others over a group/person",
"to reduce the status of another",
"to reduce the status of others",
"to regain ones health",
"to regain the health of others",
"to remain in a way of life/living condition",
"to remain in an endeavour",
"to remove the possession of others over a place/thing",
"to retain a habit/addiction",
"to retain a pleasurable activity",
"to retain a status",
"to retain control over a group/person",
"to retain influence over a group/person",
"to retain possession of a place/thing",
"to retain power",
"to retain the love of another person",
"to retain the status of others",
"to ruin the reputation of a group/person",
"to run from ones reputation",
"to shake the control of a group/person",
"to shorten one's own life",
"to spread a belief",
"to spread certain information",
"to spread information about a person/group",
"to spread information about a place/thing",
"to spread information about an endeavor/event",
"to spread knowledge",
"to spread the source of a phobia/allergy",
"to spread wealth",
"to stamp out a habit/addiction",
"to stamp out a hobby/activity",
"to start conflict/violence",
"to stay alive",
"to stay away from a group/person",
"to stay away from a place/thing",
"to stay away from a way of life/living condition",
"to stay in a group",
"to stay out of a relationship",
"to stop an endeavour/event",
"to stop the creation of a thing/place",
"to stop the formation of a group",
"to strengthen an alliance",
"to sustain a state of chaos/anarchy/conflict",
"to teach a hobby/activity",
"to teach a skill/ability",
"to uncover a hidden group/person",
"to uncover a secret/conspiracy",
"completely insane or eccentric"}