businesses={"Accounting Firm",
"Actors, Independent",
"Administrative Service Business",
"Adoption Agencies",
"Advertising Agency",
"Advertising Consulting",
"Advertising Copywriter",
"Advertising Material Distribution Services",
"Aerobic Dance and Exercise Centers",
"Agents and Managers",
"Agricultural Consultant",
"Agriculture Farm Business",
"Agriculture Fruit Farm Business",
"Agriculture Produce Farm Business",
"Air Conditioning and Heating Company",
"Air Traffic Control",
"Aircraft Charter Services",
"Aircraft Equipment Maker",
"Aircraft Manufacturing",
"Aircraft Rental and Leasing",
"Aircraft Rental Instruction",
"Aircraft Weighing Systems",
"Airport Shuttle Service",
"Airport Taxi",
"Almanac Publishers (except Exclusive Internet Publishing)",
"Alternative Health Website",
"Amateur Sports Teams, Recreational",
"Ambulance Services",
"Ambulatory Surgical and Emergency Centers",
"Amusement and Theme Parks",
"Amusement Arcades",
"Animal Daycare",
"Animal Exhibits, Live",
"Animal Food Manufacturing",
"Animal Safari Parks",
"Animated Cartoon Artists, Independent",
"Announcers, Independent Radio and Television",
"Antiques Dealer",
"Apiculture",
"Apparel Manufacturing",
"Apple Orchards",
"Appliance Repair and Maintenance",
"Appliance Rental",
"Apprenticeship Training",
"Aquarium Services",
"Aquariums",
"Arboretums",
"Archery Range",
"Architectural Engineering",
"Architectural Services",
"Archives",
"Armored Car Services",
"Art Dealers",
"Art Film Theater",
"Art Gallery",
"Art Packaging Installation",
"Art Restorers, Independent",
"Art Sales Custom Framing",
"Art School Gallery",
"Art School Museum",
"Art Shipping",
"Art Supply Store",
"Artificial Flowers Importers",
"Arts & Crafts",
"Artists, Independent",
"Astrology Tarot Card Business",
"Athletes, Independent",
"Athletic Club Facilities, Physical Fitness",
"Athletic Shoe Stores",
"Atlas Publishers",
"Auditing Services",
"Auto Body, Paint, and Interior Repair and Maintenance",
"Auto Decal Business",
"Auto Insurance Claims",
"Automated Accounting Systems",
"Automobile Dealership",
"Automobile Detailing Business",
"Automobile Driving Schools",
"Automobile Inspection Business",
"Automobile Manufacturing",
"Automobile Racing Teams",
"Automobile Restoration",
"Automotive Glass Replacement Shops",
"Automotive Oil Change and Lubrication Shops",
"Automotive Parts and Accessories Store",
"Automotive Repair",
"Aviaries",
"Aviation Clubs, Recreational",
"Baked Goods Stores",
"Ball and Roller Bearing Manufacturing",
"Ballet Dancers, Independent",
"Ballrooms",
"Banner-making",
"Bar/Club Business",
"Barber Schools",
"Barber Shops",
"Bare Printed Circuit Board Manufacturing",
"Barge Rental or Leasing",
"Baseball Clubs, Recreational",
"Basketball Clubs, Recreational",
"Bathing Beaches",
"Beach Clubs, Recreational",
"Beauty Salons",
"Beauty Supplies Stores",
"Bed-and-Breakfast Inns",
"Bee Production",
"Beef Cattle Ranching and Farming",
"Beer and Ale Merchant Wholesalers",
"Beer Cooling and Dispensing Equipment Manufacturing",
"Beer Stores",
"Beet Sugar Manufacturing",
"Berry (except Strawberry) Farming",
"Bicycle Pump Manufacturing",
"Billiard Parlors",
"Biological Product (except Diagnostic) Manufacturing",
"Bird Proofing Services",
"Bituminous Coal and Lignite Surface Mining",
"Bituminous Coal Underground Mining",
"Blankbook, Looseleaf Binders, and Devices Manufacturing",
"Blind and Shade Manufacturing",
"Blood and Organ Banks",
"Blueprinting Services",
"Boarding Houses",
"Boat Building",
"Boat Dealers",
"Boat Rental (except Pleasure)",
"Boat Rental or Leasing, Commercial",
"Boating Clubs without Marinas",
"Boccie Ball Courts",
"Body Building Studios, Physical Fitness",
"Bolt, Nut, Screw, Rivet, and Washer Manufacturing",
"Book, Periodical, and Newspaper Merchant Wholesalers",
"Book Publishers",
"Book Stores",
"Books Printing",
"Botanical Gardens",
"Bottled Water Manufacturing",
"Bowling Centers",
"Bowling Leagues or Teams, Recreational",
"Boxers, Independent Professional",
"Boxing Clubs, Recreational",
"Breakfast Cereal Manufacturing",
"Breweries",
"Brick and Structural Clay Tile Manufacturing",
"Brick, Stone, and Related Construction Material Merchant Wholesalers",
"Bridge Clubs, Recreational",
"Broadwoven Fabric Finishing Mills",
"Broadwoven Fabric Mills",
"Broilers and Other Meat Type Chicken Production",
"Broom, Brush, and Mop Manufacturing",
"Building Inspection Services",
"Building Material Dealers",
"Burial Casket Manufacturing",
"Bus and Other Motor Vehicle Transit Systems",
"Business Associations",
"Business Management Consulting Services",
"Business Schools",
"Business Service Centers",
"Business Start-up Consulting Services",
"Business Support",
"Business to Business Electronic Markets",
"Cable and Other Subscription Programming",
"Cafeterias",
"Camera Stores",
"Cameramen, Independent (Freelance)",
"Campgrounds",
"Camps (except Instructional), Day",
"Cane Sugar Refining",
"Canoeing, Recreational",
"Canvas and Related Product Mills",
"Canvas Work",
"Car Leasing",
"Car Rental",
"Car Wash",
"Carbon and Graphite Product Manufacturing",
"Carbon Black Manufacturing",
"Carbon Paper and Inked Ribbon Manufacturing",
"Carburetor, Piston, Piston Ring, and Valve Manufacturing",
"Carnival Ride Concession Operators (i.e., Supplying and Servicing in Others' Facilities)",
"Carpet and Rug Mills",
"Carpet Cleaning Services",
"Cartoonists, Independent",
"Car Wash Business",
"Casino Hotels",
"Casinos",
"Caterers",
"Cattle Feedlots",
"Caulking Compounds (except Gypsum Base) Manufacturing",
"Celebrity Spokespersons, Independent",
"Cellulosic Organic Fiber Manufacturing",
"Cement Manufacturing",
"Cement, Rubber, Manufacturing",
"Cemeteries and Crematories",
"Ceramic Wall and Floor Tile Manufacturing",
"Certified Public Accountants Offices",
"Charter Bus Industry",
"Cheese Manufacturing",
"Chicken Egg Production",
"Child Day Care Services",
"Child Guidance Agencies",
"Child Services",
"Children's and Infants' Clothing Stores",
"Chiropractors Offices",
"Chocolate and Confectionery Manufacturing from Cacao Beans",
"Choreographers, Independent",
"Cigarette Manufacturing",
"Cinematographers, Independent",
"Circular Direct Distribution Services",
"Citrus (except Orange) Groves",
"Civic and Social Organizations",
"Claims Adjusting",
"Clay and Ceramic and Refractory Minerals Mining",
"Clay Refractory Manufacturing",
"Clothing Accessories Stores",
"Coal and Other Mineral and Ore Merchant Wholesalers",
"Coastal and Great Lakes Freight Transportation",
"Coastal and Great Lakes Passenger Transportation",
"Coated and Laminated Packaging Paper and Plastics Film Manufacturing",
"Coated and Laminated Paper Manufacturing",
"Coffee Manufacturing",
"Coin-Op Laundry",
"Collection Agencies",
"College Planning Consultant",
"Comedians, Independent",
"Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance",
"Commercial and Institutional Building Construction",
"Commercial Bakeries",
"Commercial Banking",
"Commercial Flexographic Printing",
"Commercial Gravure Printing",
"Commercial, Industrial, and Institutional Electric Lighting Fixture Manufacturing",
"Commercial Laundry, Drycleaning, and Pressing Machine Manufacturing",
"Commercial Lithographic Printing",
"Commercial Photography",
"Commercial Printing",
"Commercial Screen Printing",
"Commodity Contracts Dealing",
"Communication Equipment Repair and Maintenance",
"Community Centers (except Recreational Only), Youth",
"Community Food Services",
"Community Housing Services",
"Commuter Rail Systems",
"Compact Disc (except Software) Reproducing",
"Composers, Independent",
"Compressors, Air and Gas, General Purpose-type, Manufacturing",
"Computer and Computer Peripheral Equipment and Software Merchant Wholesalers",
"Computer and Office Machine Repair and Maintenance",
"Computer Facilities Management Services",
"Computer Software Publishing and Reproduction",
"Computer Storage Device Manufacturing",
"Computer Stores",
"Computer Systems Design Services",
"Computer Terminal Manufacturing",
"Computer Training",
"Concrete Block and Brick Manufacturing",
"Concrete Pipe Manufacturing",
"Confectionery Manufacturing from Purchased Chocolate",
"Confectionery Manufacturing, Nonchocolate",
"Confectionery Merchant Wholesalers",
"Confectionery Stores",
"Conservatories, Botanical",
"Conservators, Independent",
"Construction Adhesives (except Asphalt, Gypsum Base) Manufacturing",
"Construction and Mining (except Oil Well) Machinery and Equipment Merchant Wholesalers",
"Construction Machinery and Equipment Rental and Leasing",
"Construction Machinery Manufacturing",
"Construction Sand and Gravel Mining ",
"Consulting Service",
"Consumer Electronics Repair and Maintenance",
"Consumer Lending",
"Continuing Care Retirement Communities",
"Convenience Stores",
"Convention Bureaus",
"Convention Organizers",
"Converted Paper Product Manufacturing",
"Conveyor and Conveying Equipment Manufacturing",
"Cookie Manufacturing",
"Coolers, Refrigeration, Manufacturing",
"Coolers, Water, Manufacturing",
"Copper Rolling, Drawing, and Extruding",
"Copper Wire (except Mechanical) Drawing",
"Copper Foundries (except Die-Casting)",
"Copper Ore and Nickel Ore Mining",
"Copy Shops",
"Corn Farming",
"Corporate, Subsidiary, and Regional Managing Offices",
"Correctional Institutions",
"Corrugated and Solid Fiber Box Manufacturing",
"Cosmetics Stores",
"Cosmetology Schools",
"Costume Designers, Independent Theatrical",
"Costume Rental",
"Cotton Farming",
"Cotton Ginning",
"Counters and Display Cases, Refrigerated, Manufacturing",
"Country Clubs",
"Coupon Direct Distribution Services",
"Couriers",
"Court Reporting",
"Cracker Manufacturing",
"Creamery Butter Manufacturing",
"Credit Bureaus",
"Credit Card Issuing",
"Credit Unions",
"Crocheting",
"Crop Harvesting, Primarily by Machine",
"Crops Grown Under Cover",
"Cross Stitch",
"Crown and Closure Manufacturing",
"Crude Petroleum and Natural Gas Extraction",
"Crushed and Broken Granite Mining and Quarrying",
"Crushed and Broken Limestone Mining and Quarrying",
"Curling Facilities",
"Current-Carrying Wiring Device Manufacturing",
"Curtain and Drapery Mills",
"Custody Activities",
"Custom Architectural Woodwork and Millwork Manufacturing",
"Custom Computer Programming Services",
"Custom Roll Forming",
"Cut Stock, Resawing Lumber, and Planing",
"Cut Stone and Stone Product Manufacturing",
"Cutlery and Flatware (except Precious) Manufacturing",
"Cutting Tool and Machine Tool Accessory Manufacturing",
"Cyclic Crude and Intermediate Manufacturing",
"Dairy Cattle",
"Dairy Product (except Dried or Canned) Merchant Wholesalers",
"Dairy Product Manufacturing (Dry, Condensed, and Evaporated)",
"Dance Centers, Aerobic",
"Dance Companies",
"Dance Halls",
"Dance Studio",
"Dancers, Independent",
"Data Processing Services",
"Deep Sea Freight Transportation",
"Deep Sea Passenger Transportation",
"Dehumidifiers (except Portable Electric) Manufacturing",
"Dental Equipment and Supplies Manufacturing",
"Dental Laboratories",
"Dentists Offices",
"Department Stores (except Discount Department Stores)",
"Diagnostic Imaging Centers",
"Dictionary Publishers (except Exclusive Internet Publishing)",
"Die-Cut Paper and Paperboard Office Supplies Manufacturing",
"Diet and Weight Reducing Centers",
"Digital Printing",
"Dimension Stone Mining and Quarrying",
"Direct Mail Advertising",
"Directors, Independent",
"Directory Publishers",
"Directory, Telephone, Distribution on a Contract Basis",
"Disc Jockeys, Independent",
"Discotheques (except Those Serving Alcoholic Beverages)",
"Discount Department Stores",
"Display Advertising",
"Display Cases, Refrigerated, Manufacturing",
"Distilleries",
"Document Copying Services",
"Document Preparation Services",
"Dog and Cat Food Manufacturing",
"Dog Owners, Race (i.e., Racing Dogs)",
"Dog Racing Kennels",
"Doll and Stuffed Toy Manufacturing",
"Door-to-door Distribution of Advertising Materials (e.g., Coupons, Flyers, Samples)",
"Drafting Services",
"Dried and Dehydrated Food Manufacturing",
"Drilling Oil and Gas Wells",
"Drinking Fountains, Refrigerated, Manufacturing",
"Drinking Places (Alcoholic Beverages)",
"Drive-In Motion Picture Theaters",
"Drivers, Harness or Race Car",
"Driving Ranges, Golf",
"Drug Stores",
"Drugs and Druggists' Sundries Merchant Wholesalers",
"Dry Pasta Manufacturing",
"Dry Pea and Bean Farming",
"Drycleaning and Laundry Services (except Coin-Operated)",
"Drywall and Insulation Contractors",
"Duplicating Services",
"eBay Business",
"Educational Support Services",
"Elderly Services",
"Electric Bulk Power Transmission and Control",
"Electric Housewares and Household Fan Manufacturing",
"Electric Lamp Bulb and Part Manufacturing",
"Electric Power Distribution",
"Electrical and Electronic Appliance, Television, and Radio Set Merchant Wholesalers",
"Electrical Apparatus and Equipment, Wiring Supplies, and Related Equipment Merchant Wholesalers",
"Electrical Contractors",
"Electromedical and Electrotherapeutic Apparatus Manufacturing",
"Electrometallurgical Ferroalloy Product Manufacturing",
"Electron Tube Manufacturing",
"Electronic Auctions",
"Electronic Capacitor Manufacturing",
"Electronic Coil, Transformer, and Other Inductor Manufacturing",
"Electronic Computer Manufacturing",
"Electronic Connector Manufacturing",
"Electronic Resistor Manufacturing",
"Electronic Shopping",
"Electronics Rental",
"Electronics Stores",
"Electroplating, Plating, Polishing, Anodizing, and Coloring",
"Elementary Schools",
"Elevator and Moving Stairway Manufacturing",
"Embroidery",
"Emergency and Other Relief Services",
"Emergency Medical Transportation Service, Air and Ground",
"Employment Placement Agencies",
"Encyclopedia Publishers (except Exclusive Internet Publishing)",
"Engineered Wood Member (except Truss) Manufacturing",
"Engineering Services",
"Entertainers, Independent",
"Envelope Manufacturing",
"Environment, Conservation and Wildlife Organizations",
"Environmental Consulting Services",
"Epoxy Adhesives Manufacturing",
"Ethnic Dancers, Independent",
"Ethyl Alcohol Manufacturing",
"Event Planning Service",
"Exam Preparation",
"Exercise Centers",
"Explosives Manufacturing",
"Exterminating Services",
"Fabric Coating Mills",
"Fabricated Pipe and Pipe Fitting Manufacturing",
"Fabricated Structural Metal Manufacturing",
"Facilities Support Services",
"Family Clothing Stores",
"Family Fun Centers",
"Family Planning Centers",
"Farm and Garden Machinery and Equipment Merchant Wholesalers",
"Farm Labor Contractors and Crew Leaders",
"Farm Machinery and Equipment Manufacturing",
"Farm Management Services",
"Farm Product Warehousing and Storage",
"Farm Supplies Merchant Wholesalers",
"Farm Supply Stores",
"Fastener, Button, Needle, and Pin Manufacturing",
"Fats and Oils Refining and Blending",
"Fertilizer (Mixing Only) Manufacturing",
"Fiber Can, Tube, Drum, and Similar Products Manufacturing",
"Fiber Optic Cable Manufacturing",
"Fiduciary Activities",
"Figure Skaters, Independent",
"Film Actors, Independent",
"Film Producers, Independent",
"Financial Investment Activities",
"Financial Management Consulting (except Investment Advice) Services",
"Financial Planner",
"Financial Transactions Processing, Reserve, and Clearinghouse Activities",
"Fine Arts Schools",
"Finfish Fishing",
"Finish Carpentry Contractors",
"Fire Protection",
"Fireworks Display Services",
"Fish and Seafood Merchant Wholesalers",
"Fish Hatcheries",
"Fish Markets",
"Fishing Clubs, Recreational",
"Fishing Guide Services",
"Fishing Piers",
"Fitness and Recreational Sports Centers",
"Flat Glass Manufacturing",
"Flight Training",
"Flavoring Syrup and Concentrate Manufacturing",
"Floor Covering Stores",
"Flooring Contractors",
"Floriculture Production",
"Florists",
"Flour Milling",
"Flour Mixes and Dough Manufacturing from Purchased Flour",
"Flower, Nursery Stock, and Florists' Supplies Merchant Wholesalers",
"Fluid Milk Manufacturing",
"Fluid Power Cylinder and Actuator Manufacturing",
"Fluid Power Pump and Motor Manufacturing",
"Fluid Power Valve and Hose Fitting Manufacturing",
"Flyer Direct Distribution (except Direct Mail) Services",
"Flying Clubs, Recreational",
"Folding Paperboard Box Manufacturing",
"Folk Dancers, Independent",
"Food Product Machinery Manufacturing",
"Food Service Contractors",
"Football Clubs, Recreational",
"Footwear and Leather Goods Repair",
"Footwear Merchant Wholesalers",
"Forest Nurseries",
"Forestry Machinery and Equipment Rental and Leasing",
"Formal Wear Rental",
"Fossil Fuel Electric Power Generation",
"Foster Home Placement Services",
"Fountains, Refrigerated Drinking, Manufacturing",
"Framing Contractors",
"Freezing Equipment, Industrial and Commercial-type, Manufacturing",
"Freight Brokerage",
"Fresh Fruit and Vegetable Merchant Wholesalers",
"Frozen Cakes, Pies, and Other Pastries Manufacturing",
"Frozen Fruit, Juice, and Vegetable Manufacturing",
"Frozen Specialty Food Manufacturing",
"Fruit Canning",
"Fruit Markets",
"Full-Service Restaurants",
"Fumigating Services (except Crop Fumigating)",
"Funeral Homes and Funeral Services",
"Fur and Leather Apparel Manufacturing",
"Fur-Bearing Animal and Rabbit Production",
"Furnaces, Warm Air (i.e., Forced Air), Manufacturing",
"Furniture Merchant Wholesalers",
"Furniture Stores",
"Galleries, Shooting",
"Game Stores",
"Game, Toy, and Children's Vehicle Manufacturing",
"Garden Centers",
"Gardens, Zoological or Botanical",
"Gasket, Packing, and Sealing Device Manufacturing",
"Gasoline Engine and Engine Parts Manufacturing",
"Gasoline Stations",
"Gasoline Stations with Convenience Stores",
"General Freight Trucking, Local",
"General Freight Trucking, Long-Distance, Truckload",
"General Freight Trucking, Long-Distance, Less Than Truckload",
"General Line Grocery Merchant Wholesalers",
"General Management Consulting Services",
"General Warehousing and Storage",
"Geophysical Surveying and Mapping Services",
"Ghost Writers, Independent",
"Gift Stores",
"Glass and Glazing Contractors",
"Glass Container Manufacturing",
"Glove and Mitten Manufacturing",
"Glues (except Dental) Manufacturing",
"Goat Farming",
"Gocart Tracks (i.e., Amusement Rides)",
"Gold Ore Mining",
"Golf Courses",
"Golf Courses, Miniature",
"Golf Courses, Pitch-n-putt",
"Golf Driving Ranges",
"Golfers, Independent Professional (i.e., Participating in Sports Events)",
"Grain and Field Bean Merchant Wholesalers",
"Grantmaking Foundations",
"Grape Vineyards",
"Graphic Design Services",
"Greeting Card Publishers",
"Grocery (except Convenience) Stores",
"Ground or Treated Mineral and Earth Manufacturing",
"Guide Services (i.e., Fishing, Hunting, Tourist)",
"Guide, Street Map, Publishers (except Exclusive Internet Publishing)",
"Guided Missile and Space Vehicle Manufacturing",
"Guided Missile and Space Vehicle Propulsion Unit and Propulsion Unit Parts Manufacturing",
"Gum and Wood Chemical Manufacturing",
"Gun Clubs, Recreational",
"Gymnasiums",
"Gypsum Product Manufacturing",
"Hair Salon & Day Spa",
"Hand and Edge Tool Manufacturing",
"Handball Club Facilities",
"Handbill Direct Distribution Services",
"Hardware Manufacturing",
"Hardware Merchant Wholesalers",
"Hardware Stores",
"Hardwood Veneer and Plywood Manufacturing",
"Harness Drivers",
"Hat, Cap, and Millinery Manufacturing",
"Hay Farming",
"Hazardous Waste Treatment and Disposal",
"Health and Personal Care Stores",
"Health and Welfare Funds",
"Health Club Facilities, Physical Fitness",
"Health Spas Without Accommodations, Physical Fitness",
"Health Supplement Stores",
"Heating Equipment (except Warm Air Furnaces) Manufacturing",
"Heating Equipment, Warm Air (i.e., Forced Air), Manufacturing",
"Heating Oil Dealers",
"Heavy and Civil Engineering Construction",
"Heavy Duty Truck Manufacturing",
"Herb farming, grown under cover",
"Herb farming, open field",
"Highway, Street, and Bridge Construction",
"Historical Sites",
"HMO Medical Centers",
"Hobby Stores",
"Hockey Teams, Recreational",
"Hog Farming",
"Home and Garden Equipment Repair and Maintenance",
"Home Centers",
"Home Design",
"Home Furnishing Merchant Wholesalers",
"Home Furnishings Stores",
"Home Health Care Services",
"Home Health Equipment Rental",
"Home Inspection Service",
"Homes for the Elderly",
"Horse Racing Stables",
"Horse Rental Services, Recreational Saddle",
"Horseback Riding, Recreational",
"Horses and Other Equine Production",
"Hosiery and Sock Mills",
"Hotels",
"House Slipper Manufacturing",
"Household Appliance Stores",
"Household Cooking Appliance Manufacturing",
"Household Furniture (except Wood and Metal) Manufacturing",
"Household Laundry Equipment Manufacturing",
"Household Refrigerator and Home Freezer Manufacturing",
"Household Textile Product Mills",
"Household Vacuum Cleaner Manufacturing",
"Human Resources and Executive Search Consulting Services",
"Human Rights Organizations",
"Humidifying Equipment (except Portable) Manufacturing",
"Hunting and Trapping",
"Hunting Clubs, Recreational",
"Hunting Guide Services",
"Hydroelectric Power Generation",
"Hydroponic crop farming",
"Ice Cream and Frozen Dessert Manufacturing",
"Ice Hockey Clubs, Recreational",
"Ice Making Machinery Manufacturing",
"Ice Manufacturing",
"Ice Skating Rinks",
"Import/Export Business",
"Indoor Play Areas",
"Industrial and Commercial Fan and Blower Manufacturing",
"Industrial and Personal Service Paper Merchant Wholesalers",
"Industrial Building Construction",
"Industrial Design Services",
"Industrial Gas Manufacturing",
"Industrial Launderers",
"Industrial Machinery and Equipment Merchant Wholesalers",
"Industrial Mold Manufacturing",
"Industrial Pattern Manufacturing",
"Industrial Process Furnace and Oven Manufacturing",
"Industrial Sand Mining",
"Industrial Supplies Merchant Wholesalers",
"Industrial Truck, Tractor, Trailer, and Stacker Machinery Manufacturing",
"Industrial Valve Manufacturing",
"Infants' Cut and Sew Apparel Manufacturing",
"Inland Water Freight Transportation",
"Inland Water Passenger Transportation",
"Inorganic Chemical Manufacturing",
"Inorganic Dye and Pigment Manufacturing",
"Institutional Furniture Manufacturing",
"Instrument Manufacturing for Measuring and Testing Electricity and Electrical Signals",
"Instruments and Related Products Manufacturing for Measuring, Displaying, and Controlling Industrial Process Variables",
"Insurance Agencies and Brokerages",
"Integrated Record Production/Distribution",
"Interior Design Services",
"International Trade Financing",
"Interpretive Dancers, Independent",
"Interurban and Rural Bus Transportation",
"Investigation Services",
"Investment Advice",
"Investment Banking",
"In-Vitro Diagnostic Substance Manufacturing",
"Iron Foundries",
"Iron Ore Mining",
"Irradiation Apparatus Manufacturing",
"Janitorial Services",
"Jazz Dancers, Independent",
"Jewelers' Material and Lapidary Work Manufacturing",
"Jewelry Manufacturing",
"Jewelry Stores",
"Jewelry, Watch, Precious Stone, and Precious Metal Merchant Wholesalers",
"Jockeys, Horse Racing",
"Joint Compounds (except Gypsum Base) Manufacturing",
"Journalists, Independent (Freelance)",
"Jukebox Concession Operators (i.e., Supplying and Servicing in Others' Facilities)",
"Kaolin and Ball Clay Mining",
"Kayaking, Recreational",
"Kennels, Dog Racing",
"Kidney Dialysis Centers",
"Kitchen Utensil, Pot, and Pan Manufacturing",
"Knit Fabric and Lace Mills",
"Knitting",
"Labeling Services",
"Labor Unions and Similar Labor Organizations",
"Lace-making",
"Laminated Aluminum Foil Manufacturing for Flexible Packaging Uses",
"Land Subdivision",
"Landscape Architectural Services",
"Language Schools",
"Laser Surgery Centers",
"Lawn and Garden Tractor and Home Lawn and Garden Equipment Manufacturing",
"Lawn Care/Landscaping Business",
"Lawyers Offices",
"Lead Ore and Zinc Ore Mining",
"Lead Pencil and Art Good Manufacturing",
"Leather and Hide Tanning and Finishing",
"Leather Good Manufacturing",
"Leather Goods Stores",
"Libraries",
"Light Truck and Utility Vehicle Manufacturing",
"Lighting Technicians, Theatrical, Independent",
"Lime Manufacturing",
"Limited-Service Restaurants",
"Limousine Service",
"Line-Haul Railroads",
"Linen Supply",
"Liquefied Petroleum Gas (Bottled Gas) Dealers",
"Liquor Stores",
"Livestock Merchant Wholesalers",
"Local Messengers and Local Delivery",
"Lockers, Refrigerated, Manufacturing",
"Locksmiths",
"Logging",
"Lucet",
"Luggage Manufacturing",
"Luggage Stores",
"Lumber, Plywood, Millwork, and Wood Panel Merchant Wholesalers",
"Machine Shops",
"Machine Tool (Metal Cutting Types) Manufacturing",
"Machine Tool (Metal Forming Types) Manufacturing",
"Macrame",
"Magicians, Independent",
"Magnetic and Optical Recording Media Manufacturing",
"Mail-Order Houses",
"Mailing List Publishers",
"Malt Manufacturing",
"Management Consulting Services",
"Management Development Training",
"Manifold Business Forms Printing",
"Manufactured (Mobile) Home Dealers",
"Manufactured Home (Mobile Home) Manufacturing",
"Map Publishers (except Exclusive Internet Publishing)",
"Marinas",
"Marine Cargo Handling",
"Marketing Consulting Services",
"Marketing Research",
"Marking Device Manufacturing",
"Masonry Contractors",
"Materials Recovery Facilities",
"Mattress Manufacturing",
"Mayonnaise, Dressing, and Other Prepared Sauce Manufacturing",
"Measuring and Dispensing Pump Manufacturing",
"Meat and Meat Product Merchant Wholesalers",
"Meat Byproduct Processing and Rendering",
"Meat Markets",
"Meat Processed from Carcasses",
"Mechanical Power Transmission Equipment Manufacturing",
"Media Buying Agencies",
"Media Representatives",
"Medical Claims Billing Service",
"Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesalers",
"Medical Hospitals",
"Medical Laboratories",
"Medical Office Management Consulting Services or Consultants",
"Medicinal and Botanical Manufacturing",
"Melon Farming",
"Menageries",
"Men's and Boys' Clothing and Furnishings Merchant Wholesalers",
"Men's and Boys' Cut and Sew Apparel Contractors",
"Men's and Boys' Cut and Sew Other Outerwear Manufacturing",
"Men's and Boys' Cut and Sew Shirt (except Work Shirt) Manufacturing",
"Men's and Boys' Cut and Sew Suit, Coat, and Overcoat Manufacturing",
"Men's and Boys' Cut and Sew Trouser, Slack, and Jean Manufacturing",
"Men's and Boys' Cut and Sew Underwear and Nightwear Manufacturing",
"Men's and Boys' Cut and Sew Work Clothing Manufacturing",
"Men's and Boys' Neckwear Manufacturing",
"Men's Clothing Stores",
"Men's Footwear (except Athletic) Manufacturing",
"Mental Health Practitioners Offices (except Physicians)",
"Metal Can Manufacturing",
"Metal Coating, Engraving (except Jewelry and Silverware), and Allied Services to Manufacturers",
"Metal Heat Treating",
"Metal Household Furniture Manufacturing",
"Metal Service Centers and Other Metal Merchant Wholesalers",
"Metal Stamping",
"Metal Tank (Heavy Gauge) Manufacturing",
"Metal Window and Door Manufacturing",
"Metalworking",
"Military Armored Vehicle, Tank, and Tank Component Manufacturing",
"Milk Production",
"Millwork (including Flooring)",
"Mineral Wool Manufacturing",
"Miniature Golf Courses",
"Mining Machinery and Equipment Manufacturing",
"Mining Machinery and Equipment Rental and Leasing",
"Miniwarehouses and Self-Storage Units Lessors",
"Mixed Mode Transit Systems",
"Mobile Food Services",
"Models, Independent",
"Mortgage and Nonmortgage Loan Brokers",
"Mosquito Eradication Services",
"Motels",
"Motion Picture and Video Distribution",
"Motion Picture and Video Production",
"Motion Picture Directors, Independent",
"Motion Picture Producers, Independent",
"Motion Picture Theaters (except Drive-Ins)",
"Motivational Speakers, Independent",
"Motor and Generator Manufacturing",
"Motor Home Manufacturing",
"Motor Vehicle Air Conditioning Manufacturing",
"Motor Vehicle Body Manufacturing",
"Motor Vehicle Brake System Manufacturing",
"Motor Vehicle Metal Stamping",
"Motor Vehicle Parts (Used) Merchant Wholesalers",
"Motor Vehicle Seating and Interior Trim Manufacturing",
"Motor Vehicle Steering and Suspension Components (except Spring) Manufacturing",
"Motor Vehicle Supplies and New Parts Merchant Wholesalers",
"Motor Vehicle Towing",
"Motor Vehicle Transmission and Power Train Parts Manufacturing",
"Motorcycle, Bicycle, and Parts Manufacturing",
"Motorcycle Dealers",
"Motorcycle Racing Teams",
"Motorcycle Repair and Maintenance Services",
"Mountain Hiking, Recreational",
"Museums",
"Mushroom Production",
"Music Arrangers, Independent",
"Music Directors, Independent",
"Music Publishers",
"Musical Groups and Artists",
"Musical Instrument and Supplies Stores",
"Musical Instrument Manufacturing",
"Nail Salons",
"Narrow Fabric Mills",
"Natural Gas Distribution",
"Natural Gas Liquid Extraction",
"Nature Parks",
"Navigational Services to Shipping",
"Needlepoint",
"Needlework Stores",
"New Car Dealers",
"New Housing Operative Builders",
"New Multifamily Housing Construction",
"New Single-Family Housing Construction",
"News Dealers and Newsstands",
"News Syndicates",
"Newspaper Columnists, Independent (Freelance)",
"Newspaper Publishers",
"Newsprint Mills",
"Nightclubs without Alcoholic Beverages",
"Nightwear Knitting Mills",
"Nitrogenous Fertilizer Manufacturing",
"Nonalcoholic Beverage Bars",
"Noncellulosic Organic Fiber Manufacturing",
"Noncurrent-Carrying Wiring Device Manufacturing",
"Nonferrous (except Aluminum) Die-Casting Foundries",
"Nonferrous Forging",
"Nonferrous Metal (except Copper and Aluminum) Rolling, Drawing, and Extruding",
"Nonfolding Sanitary Food Container Manufacturing",
"Nonresidential Buildings (except Miniwarehouses) Lessors",
"Nonresidential Property Managers",
"Nonscheduled Chartered Freight Air Transportation",
"Nonscheduled Chartered Passenger Air Transportation",
"Nonupholstered Wood Household Furniture Manufacturing",
"Nonwoven Fabric Mills",
"Notaries Offices",
"Novelty Stores",
"Nuclear Electric Power Generation",
"Nudist Camps without Accommodations",
"Nursery Production",
"Nurseries",
"Nursing Care Facilities",
"Nut Stores",
"Oat Farming",
"Observation Towers",
"Occupational Therapists Offices",
"Office Administrative Services",
"Office Equipment Merchant Wholesalers",
"Office Furniture (except Wood) Manufacturing",
"Office Machinery and Equipment Rental and Leasing",
"Office Machinery Manufacturing",
"Office Supplies Stores",
"Oil and Gas Field Machinery and Equipment Manufacturing ",
"Oil and Gas Pipeline Construction",
"Oilseed (except Soybean) Farming",
"Oilseed Processing",
"One-Hour Photofinishing",
"Online Business",
"Ophthalmic Goods Manufacturing",
"Ophthalmic Goods Merchant Wholesalers",
"Optical Goods Stores",
"Optical Instrument and Lens Manufacturing",
"Optometrists Offices",
"Orange Groves",
"Orchestra Conductors, Independent",
"Organic Chemical Manufacturing",
"Ornamental and Architectural Metal Work Manufacturing",
"Outdoor Adventure Operations (e.g., White Water Rafting) without Accommodations",
"Outdoor Power Equipment Stores",
"Outerwear Knitting Mills",
"Outpatient Mental Health and Substance Abuse Centers",
"Overhead Traveling Crane, Hoist, and Monorail System Manufacturing",
"Pack Trains (i.e., Trail Riding), Recreational",
"Packaged Frozen Food Merchant Wholesalers",
"Packaging Machinery Manufacturing",
"Packaging Services",
"Packing and Crating",
"Paint and Coating Manufacturing",
"Paint Sprayers (i.e., Compressor and Spray Gun Unit) Manufacturing",
"Paint Stores",
"Paint, Varnish, and Supplies Merchant Wholesalers",
"Painters (i.e., Artists), Independent",
"Painting and Wall Covering Contractors",
"Painting Restorers, Independent",
"Pamphlet Publishers (except Exclusive Internet Publishing)",
"Paper (except Newsprint) Mills",
"Paper Industry Machinery Manufacturing",
"Paperboard Mills",
"Para Sailing, Recreational",
"Parking Lots and Garages",
"Parks, Wild Animal",
"Pastes, Adhesive, Manufacturing",
"Patchwork",
"Patrol Services",
"Payroll Services",
"Peanut Butter Manufacturing",
"Peanut Farming",
"Pen and Mechanical Pencil Manufacturing",
"Performers (i.e., Entertainers), Independent",
"Performing Artists, Independent",
"Perfume Stores",
"Periodical Publishers",
"Perishable Prepared Food Manufacturing",
"Pension Funds",
"Personal Concierge / Shopper",
"Personal Leather Good (except Women's Handbag and Purse) Manufacturing",
"Persons with Disabilities Services",
"Pest Control Services",
"Pesticide and Other Agricultural Chemical Manufacturing",
"Pet Business",
"Pet and Pet Supplies Stores",
"Petrochemical Manufacturing",
"Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Stations and Terminals)",
"Petroleum Bulk Stations and Terminals",
"Petroleum Lubricating Oil and Grease Manufacturing",
"Petroleum Refineries",
"Petting Zoos",
"Pharmaceutical Preparation Manufacturing",
"Pharmacies",
"Phosphate Rock Mining",
"Phosphatic Fertilizer Manufacturing",
"Photo Journalists, Independent (Freelance)",
"Photocopying Services",
"Photofinishing Laboratories (except One-Hour)",
"Photographers, Independent Artistic",
"Photographic and Photocopying Equipment Manufacturing",
"Photographic Equipment and Supplies Merchant Wholesalers",
"Photographic Supplies Stores",
"Photographic Film, Paper, Plate, and Chemical Manufacturing",
"Photography Studios, Portrait",
"Physical Fitness Sports Club Facilities",
"Physical Therapists Offices ",
"Physicians Offices (except Mental Health Specialists)",
"Physicians Offices, Mental Health Specialists",
"Picnic Grounds",
"Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers",
"Piece Goods Stores",
"Pig Farming",
"Pinball Arcades",
"Pinball Machine Concession Operators (i.e., Supplying and Servicing in Others' Facilities)",
"Ping Pong Parlors",
"Pipe Sealing Compounds Manufacturing",
"Pipeline Transportation of Crude Oil ",
"Pipeline Transportation of Natural Gas",
"Pipeline Transportation of Refined Petroleum Products",
"Plastics and Rubber Industry Machinery Manufacturing",
"Plastics Bottle Manufacturing",
"Plastics Footwear Manufacturing",
"Plastics Material and Resin Manufacturing",
"Plastics Materials and Basic Forms and Shapes Merchant Wholesalers",
"Plastics Packaging Film and Sheet (including Laminated) Manufacturing",
"Plastics Pipe and Pipe Fitting Manufacturing",
"Plastics Plumbing Fixture Manufacturing",
"Plate Work Manufacturing",
"Playwrights, Independent",
"Plumbers' Putty Manufacturing",
"Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Wholesalers",
"Plumbing Fixture Fitting and Trim Manufacturing",
"Plumbing, Heating, and Air-Conditioning Contractors",
"Podiatrists Offices",
"Poets, Independent",
"Polish and Other Sanitation Good Manufacturing",
"Political Cartoonists, Independent",
"Political Organizations",
"Polystyrene Foam Product Manufacturing",
"Pool Halls",
"Porcelain Electrical Supply Manufacturing",
"Port and Harbor Operations",
"Portfolio Management",
"Postal Service",
"Postharvest Crop Activities (except Cotton Ginning)",
"Potash, Soda, and Borate Mineral Mining",
"Potato Farming",
"Poultry Hatcheries",
"Poultry and Poultry Product Merchant Wholesalers",
"Poultry Processing",
"Poured Concrete Foundation and Structure Contractors",
"Power and Communication Line Construction",
"Power Boiler and Heat Exchanger Manufacturing",
"Power, Distribution, and Specialty Transformer Manufacturing",
"Power-Driven Handtool Manufacturing",
"Power (i.e., Pressure) Washer Units Manufacturing",
"Precision Turned Product Manufacturing",
"Prefabricated Metal Building and Component Manufacturing",
"Prefabricated Wood Building Manufacturing",
"Prepress Services",
"Prerecorded Compact Disc (except Software), Tape, and Record Reproducing",
"Prerecorded Tape, Compact Disc, and Record Stores",
"Primary Battery Manufacturing",
"Printed Circuit Assembly (Electronic Assembly) Manufacturing",
"Printing and Writing Paper Merchant Wholesalers",
"Printing Ink Manufacturing",
"Printing Machinery and Equipment Manufacturing",
"Private Households",
"Private Mail Centers",
"Process, Physical Distribution, and Logistics Consulting Services",
"Producers, Independent",
"Professional Athletes, Independent (i.e., Participating in Sports Events)",
"Professional Organizations",
"Professional Employer Organizations",
"Professional Schools",
"Professional Training",
"Property Manager",
"Psychiatric Hospitals",
"Public Opinion Polling",
"Public Relations Agencies",
"Publishing, Book",
"Pulp Mills",
"Pump and Pumping Equipment Manufacturing",
"Quick Printing",
"Quilting",
"Race Car Drivers",
"Race Car Owners (i.e., Racing Cars)",
"Race Dog Owners (i.e., Racing Dogs)",
"Racehorse Owners (i.e., Racing Horses)",
"Racehorse Trainers",
"Racetracks",
"Racetracks, Slot Car (i.e., Amusement Devices)",
"Raceways, Gocart (i.e., Amusement Rides)",
"Racing Stables, Horse",
"Racing Teams (e.g., Automobile, Motorcycle, Snowmobile)",
"Racquetball Club Facilities",
"Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing",
"Radio Commentators, Independent",
"Radio Networks",
"Radio Stations",
"Radio, Television, and Other Electronics Stores",
"Railroad Car Rental and Leasing",
"Railroad Rolling Stock Manufacturing",
"Ready-Mix Concrete Manufacturing",
"Real Estate Agent",
"Real Estate Appraisers Offices",
"Real Estate Credit",
"Reconstituted Wood Product Manufacturing",
"Record Producers, Independent",
"Record Production",
"Record Reproducing",
"Record Stores",
"Recording Technicians, Independent",
"Records Management Consulting Services",
"Recreation Instruction",
"Recreational Camps",
"Recreational Camps without Accommodations",
"Recreational Day Camps (except Instructional)",
"Recreational Goods Rental",
"Recreational Sports Centers",
"Recreational Sports Teams and Clubs",
"Recreational Vehicle Dealers",
"Recyclable Material Merchant Wholesalers",
"Referees and Umpires",
"Refrigerated Warehousing and Storage",
"Refrigeration Equipment and Supplies Merchant Wholesalers",
"Refrigeration Equipment, Industrial and Commercial-type, Manufacturing",
"Relay and Industrial Control Manufacturing",
"Religious Organizations",
"Remediation Services",
"Rental Centers",
"Reorganizational consulting services",
"Reporters, Independent (Freelance)",
"Repossession Services",
"Reprographic Services",
"Reptile Exhibits",
"Rescue Services",
"Research and Development in the Social Sciences and Humanities",
"Reservation Services",
"Residential Buildings and Dwellings Lessors",
"Residential Electric Lighting Fixture Manufacturing",
"Residential Mental Health Facilities",
"Residential Mental Retardation Facilities",
"Residential Property Managers",
"Residential Remodelers",
"Residential Substance Abuse Facilities",
"Resilient Floor Covering Manufacturing",
"Restaurant and Food Business",
"Retail Bakeries",
"Retail Store",
"Reupholstery and Furniture Repair",
"Rice Farming",
"Rice Milling",
"Riding Clubs, Recreational",
"Riding Stables",
"Rifle Clubs, Recreational",
"River Rafting, Recreational",
"Roasted Nuts Manufacturing",
"Rolled Steel Shape Manufacturing",
"Roller Skating Rinks",
"Rolling Mill Machinery and Equipment Manufacturing",
"Roofing Contractors",
"Roofing, Siding, and Insulation Material Merchant Wholesalers",
"Room Air-conditioners Manufacturing",
"Rooming Houses",
"Rope, Cordage, and Twine Mills",
"Rowing Clubs, Recreational",
"Rubber and Plastics Hoses and Belting Manufacturing",
"Rubber Cement Manufacturing",
"Rubber Footwear Manufacturing",
"Rubber Product Manufacturing for Mechanical Use",
"Rug Making",
"RV (Recreational Vehicle) Parks",
"Saddle Horse Rental Services, Recreational",
"Sailing Clubs without Marinas",
"Sales Financing",
"Sample Direct Distribution Services",
"Sanitary Paper Product Manufacturing",
"Satellite Telecommunications",
"Savings Institutions",
"Saw Blade and Handsaw Manufacturing",
"Sawmill and Woodworking Machinery Manufacturing",
"Sawmills",
"Scale and Balance (except Laboratory) Manufacturing",
"Scenery Designers, Independent Theatrical",
"Scenic and Sightseeing Transportation, Land",
"Scenic and Sightseeing Transportation, Water",
"Scheduled Freight Air Transportation",
"Scheduled Passenger Air Transportation",
"Schiffli Machine Embroidery",
"School and Employee Bus Transportation",
"Screenplay Writers, Independent",
"Script Writers, Independent",
"Sculptors, Independent",
"Sea Kayaking, Recreational",
"Seafood Canning",
"Seafood Markets",
"Seafood Processing, Fresh and Frozen",
"Search, Detection, Navigation, Guidance, Aeronautical, and Nautical System and Instrument Manufacturing",
"Secondary Market Financing",
"Secondary Schools",
"Secretarial Schools",
"Securities Brokerage",
"Securities Dealing",
"Security Guards",
"Security Systems Services",
"Self-help Organizations, Youth",
"Semiconductor and Related Device Manufacturing",
"Semiconductor Machinery Manufacturing",
"Senior Care Services",
"Septic Tank and Related Services",
"Service Establishment Equipment and Supplies Merchant Wholesalers",
"Set Designers, Independent Theatrical",
"Setup Paperboard Box Manufacturing",
"Sewage Treatment Facilities",
"Sewing Stores",
"Sheep Farming",
"Sheer Hosiery Mills",
"Sheet Metal Work Manufacturing",
"Shellfish Farming",
"Ship Building and Repairing",
"Ship Rental or Leasing without Operators",
"Shoe Stores",
"Shooting Clubs, Recreational",
"Shooting Galleries",
"Short Line Railroads",
"Showcase, Partition, Shelving, and Locker Manufacturing",
"Showcases, Refrigerated, Manufacturing",
"Siding Contractors",
"Sign Manufacturing",
"Silver Ore Mining",
"Silverware and Hollowware Manufacturing",
"Site Location Consulting Services",
"Site Preparation Contractors",
"Site Selection Consulting Services",
"Skeet Shooting Facilities",
"Sketch Artists, Independent",
"Skiers, Independent (i.e., Participating in Sports Events)",
"Skiing Facilities",
"Small Arms Ammunition Manufacturing",
"Small Arms Manufacturing",
"Snack Bars",
"Snack Food Manufacturing",
"Snow Making Machinery Manufacturing",
"Snowmobile Racing Teams",
"Snowmobiling, Recreational",
"Soccer Clubs, Recreational",
"Soda Fountain Cooling and Dispensing Equipment Manufacturing",
"Soap and Other Detergent Manufacturing",
"Soft Drink Manufacturing",
"Software Publishers",
"Software Reproducing",
"Software Stores",
"Softwood Veneer and Plywood Manufacturing",
"Soil Preparation, Planting, and Cultivating",
"Solid Waste Collection",
"Solid Waste Combustors and Incinerators",
"Solid Waste Landfill",
"Song Writers, Independent",
"Sound Recording Studios",
"Souvenir Stores",
"Soybean Farming",
"Soybean Processing",
"Space Research and Technology",
"Spas Without Accommodations, Fitness",
"Speakers, Independent",
"Special Die and Tool, Die Set, Jig, and Fixture Manufacturing",
"Special Effect Technicians, Independent",
"Special Needs Transportation",
"Specialized Freight (except Used Goods) Trucking, Local",
"Specialized Freight (except Used Goods) Trucking, Long-Distance",
"Specialty Canning",
"Specialty Food Stores",
"Specialty Hospitals",
"Specialty Travel and Tours Business",
"Speech Therapists Offices",
"Speed Changer, Industrial High-Speed Drive, and Gear Manufacturing",
"Spice and Extract Manufacturing",
"Spinning",
"Sporting and Athletic Goods Manufacturing",
"Sporting and Recreational Goods and Supplies Merchant Wholesalers",
"Sporting Goods Stores",
"Sports Announcers, Independent",
"Sports Club Facilities, Physical Fitness",
"Sports Instruction",
"Sports Professionals, Independent (i.e., Participating in Sports Events)",
"Sports Recreation Guide Services",
"Sports Teams and Clubs",
"Sports Tour Operators",
"Sports Trainers",
"Sprayers, Manual Pump, General Purpose-type, Manufacturing",
"Spring (Heavy Gauge) Manufacturing",
"Spring (Light Gauge) Manufacturing",
"Squash Club Facilities",
"Stables, Horse Racing",
"Stables, Riding",
"Staffing Service Business",
"Stage Set (e.g., Concert, Motion Picture, Television) Erecting and Dismantling, Independent",
"Standup Comedians, Independent",
"Stationery and Office Supplies Merchant Wholesalers",
"Stationery Stores",
"Stationery, Tablet, and Related Product Manufacturing",
"Steam and Air-Conditioning Supply",
"Steamship Rental or Leasing without Operators",
"Steel Foundries",
"Steel Wire Drawing",
"Stenotype Services",
"Stock Car Racing Teams",
"Storage Battery Manufacturing",
"Storytellers, Independent",
"Strategic Planning Consulting Services",
"Strawberry Farming",
"Strength Development Centers",
"Structural Steel and Precast Concrete Contractors",
"Substance Abuse Hospitals",
"Sugar Beet Farming",
"Sugarcane Farming",
"Sugarcane Mills",
"Supermarkets",
"Supercenters",
"Surface Active Agent Manufacturing",
"Surface-Coated Paperboard Manufacturing",
"Surgical and Medical Instrument Manufacturing",
"Surgical Appliance and Supplies Manufacturing",
"Surgical Hospitals",
"Surveying and Mapping (except Geophysical) Services",
"Swimming Pools",
"Switchgear and Switchboard Apparatus Manufacturing",
"Synthetic Organic Dye and Pigment Manufacturing",
"Synthetic Rubber Manufacturing",
"Tanker rental or leasing",
"Tape Reproducing",
"Tapestry",
"Tax Preparation Services",
"Taxi Service",
"Taxidermists, Independent",
"Tea Manufacturing",
"Technical Manual and Paperback Book Publishers (except Exclusive Internet Publishing)",
"Technical Schools",
"Technical Writers, Independent",
"Teen Outreach Services",
"Telecommunications Resellers",
"Telemarketing Bureaus",
"Telephone Answering Services",
"Telephone Apparatus Manufacturing",
"Telephone Directory Distribution Services, Door-to-door",
"Teleproduction and Other Postproduction Services",
"Television Broadcasting",
"Television Producers, Independent",
"Television Stores",
"Temporary Help Services",
"Temporary Shelters",
"Tennis Club Facilities",
"Tennis Courts",
"Tennis Professionals, Independent (i.e., Participating in Sports Events)",
"Termite Control Services",
"Testing Laboratories",
"Textile and Fabric Finishing (except Broadwoven Fabric) Mills",
"Textile Bag Mills",
"Textile Machinery Manufacturing",
"Theater Companies and Dinner Theaters",
"Theme Parks",
"Thread Mills",
"Tile Adhesives Manufacturing",
"Tile and Terrazzo Contractors",
"Timber Tract Operations",
"Tire and Tube Merchant Wholesalers",
"Tire Cord and Tire Fabric Mills",
"Tire Dealers",
"Tire Manufacturing (except Retreading)",
"Tire Retreading",
"Title Abstract and Settlement Offices",
"Tobacco and Tobacco Product Merchant Wholesalers",
"Tobacco Farming",
"Tobacco Stemming and Redrying",
"Tobacco Stores",
"Toilet Preparation Manufacturing",
"Tortilla Manufacturing",
"Totalizing Fluid Meter and Counting Device Manufacturing",
"Tour Operators",
"Tourist Guide Services",
"Towboat Rental or Leasing",
"Toy and Hobby Goods and Supplies Merchant Wholesalers",
"Toy Stores",
"Trade Schools",
"Trade Show Organizers",
"Tradebinding and Related Work",
"Trail Riding, Recreational",
"Training Race Dogs",
"Training Racehorses",
"Trampoline Facilities, Recreational",
"Translation and Interpretation Services",
"Transmission Repair Shops, Automotive",
"Transportation Equipment and Supplies (except Motor Vehicle) Merchant Wholesalers",
"Trapshooting Facilities, Recreational",
"Trauma Centers",
"Travel Agencies",
"Travel Arrangement Services",
"Travel Tour Operators",
"Travel Trailer and Camper Manufacturing",
"Tree Nut Farming",
"Tree Production",
"Truck Trailer Manufacturing",
"Truck, Utility Trailer, and RV (Recreational Vehicle) Rental and Leasing",
"Truss Manufacturing",
"Trust Custody Activities",
"Trusts, Estates, and Agency Accounts",
"Tugboat Rental or Leasing",
"Turbine and Turbine Generator Set Units Manufacturing",
"Turkey Production",
"Tutoring",
"Uncoated Paper and Multiwall Bag Manufacturing",
"Underwear Knitting Mills",
"Upholstered Household Furniture Manufacturing",
"Upholstery Cleaning Services",
"Uranium-Radium-Vanadium Ore Mining",
"Urethane and Other Foam Product (except Polystyrene) Manufacturing",
"Used Car Dealers",
"Used Household and Office Goods Moving",
"Used Merchandise Stores",
"Vacation Camps",
"Vacuum Pumps (except Laboratory) Manufacturing",
"Vegetable Canning",
"Vegetable (except Potato) Farming",
"Vegetable Markets",
"Vehicular Lighting Equipment Manufacturing",
"Vending Machine Operators",
"Veterinary Services",
"Video Tape and Disc Rental",
"Visitors Bureaus",
"Vitreous China, Fine Earthenware, and Other Pottery Product Manufacturing",
"Vocational Rehabilitation Services",
"Voluntary Health Organizations",
"Wallpaper Stores",
"Warehouse Clubs",
"Warm Air Heating and Air-Conditioning Equipment and Supplies Merchant Wholesalers",
"Watch, Clock, and Part Manufacturing",
"Water and Sewer Line Construction",
"Water (i.e., Drinking) Coolers, Mechanical, Manufacturing",
"Water Supply and Irrigation Systems",
"Waterslides (i.e., Amusement Rides)",
"Wave Pools",
"Weaving",
"Web Design",
"Web Hosting Services",
"Wedding Consultant",
"Weft Knit Fabric Mills",
"Weight Training Centers",
"Welding and Soldering Equipment Manufacturing",
"Wet Corn Milling",
"Wheat Farming",
"White Water Rafting, Recreational",
"Wholesale Distribution",
"Wild Animal Parks",
"Wildlife Artists, Independent",
"Window Treatment Stores",
"Wine and Distilled Alcoholic Beverage Merchant Wholesalers",
"Wine Stores",
"Wineries",
"Wired Telecommunications Carriers",
"Wireless Telecommunications Carriers (except Satellite)",
"Women's and Girls' Cut and Sew Blouse and Shirt Manufacturing",
"Women's and Girls' Cut and Sew Dress Manufacturing",
"Women's and Girls' Cut and Sew Lingerie, Loungewear, and Nightwear Manufacturing",
"Women's and Girls' Cut and Sew Other Outerwear Manufacturing",
"Women's and Girls' Cut and Sew Suit, Coat, Tailored Jacket, and Skirt Manufacturing",
"Women's, Children's, and Infants' Clothing and Accessories Merchant Wholesalers",
"Women's Clothing Stores",
"Women's Footwear (except Athletic) Manufacturing",
"Women's, Girls', and Infants' Cut and Sew Apparel Contractors",
"Women's Handbag and Purse Manufacturing",
"Wood Container and Pallet Manufacturing",
"Wood Kitchen Cabinet and Countertop Manufacturing",
"Wood Office Furniture Manufacturing",
"Wood Preservation",
"Wood Product Manufacturing",
"Wood Television, Radio, and Sewing Machine Cabinet Manufacturing",
"Wood Window and Door Manufacturing",
"Wrestlers, Independent Professional",
"Writers of Advertising Copy, Independent",
"Writers, Independent (Freelance)",
"Yacht Clubs",
"Yarn Spinning Mills",
"Yarn Texturizing, Throwing, and Twisting Mills",
"Youth Centers ",
"Youth Guidance Organizations",
"Youth Self-help Organizations",
"Youth Services",
"Youth Sports Leagues or Teams",
"Zoological Gardens",
"Zoos"}